export const winterOlympicsData = [
  {
    year: 1924,
    maleQuantity: 10,
    femaleQuantity: 1,
    sports: [
      { gender: "F", name: "Figure Skating" },
      { gender: "M", name: "Ice Hockey" },
      { gender: "M", name: "Curling" },
      { gender: "M", name: "Bobsleigh" },
      { gender: "M", name: "Military Ski Patrol" },
      { gender: "M", name: "Figure Skating" },
      { gender: "M", name: "Ski Jumping" },
      { gender: "M", name: "Alpinism" },
      { gender: "M", name: "Cross Country Skiing" },
      { gender: "M", name: "Nordic Combined" },
      { gender: "M", name: "Speed Skating" }
    ],
    city: "Chamonix"
  },
  {
    year: 1928,
    maleQuantity: 8,
    femaleQuantity: 1,
    sports: [
      { gender: "F", name: "Figure Skating" },
      { gender: "M", name: "Ice Hockey" },
      { gender: "M", name: "Ski Jumping" },
      { gender: "M", name: "Cross Country Skiing" },
      { gender: "M", name: "Speed Skating" },
      { gender: "M", name: "Figure Skating" },
      { gender: "M", name: "Bobsleigh" },
      { gender: "M", name: "Nordic Combined" },
      { gender: "M", name: "Skeleton" }
    ],
    city: "Sankt Moritz"
  },
  {
    year: 1932,
    maleQuantity: 7,
    femaleQuantity: 1,
    sports: [
      { gender: "F", name: "Figure Skating" },
      { gender: "M", name: "Ice Hockey" },
      { gender: "M", name: "Figure Skating" },
      { gender: "M", name: "Speed Skating" },
      { gender: "M", name: "Ski Jumping" },
      { gender: "M", name: "Bobsleigh" },
      { gender: "M", name: "Nordic Combined" },
      { gender: "M", name: "Cross Country Skiing" }
    ],
    city: "Lake Placid"
  },
  {
    year: 1936,
    maleQuantity: 8,
    femaleQuantity: 2,
    sports: [
      { gender: "F", name: "Figure Skating" },
      { gender: "F", name: "Alpine Skiing" },
      { gender: "M", name: "Bobsleigh" },
      { gender: "M", name: "Alpine Skiing" },
      { gender: "M", name: "Ski Jumping" },
      { gender: "M", name: "Ice Hockey" },
      { gender: "M", name: "Figure Skating" },
      { gender: "M", name: "Speed Skating" },
      { gender: "M", name: "Cross Country Skiing" },
      { gender: "M", name: "Nordic Combined" }
    ],
    city: "Garmisch-Partenkirchen"
  },
  {
    year: 1948,
    maleQuantity: 9,
    femaleQuantity: 2,
    sports: [
      { gender: "F", name: "Figure Skating" },
      { gender: "F", name: "Alpine Skiing" },
      { gender: "M", name: "Ice Hockey" },
      { gender: "M", name: "Speed Skating" },
      { gender: "M", name: "Figure Skating" },
      { gender: "M", name: "Skeleton" },
      { gender: "M", name: "Bobsleigh" },
      { gender: "M", name: "Alpine Skiing" },
      { gender: "M", name: "Cross Country Skiing" },
      { gender: "M", name: "Nordic Combined" },
      { gender: "M", name: "Ski Jumping" }
    ],
    city: "Sankt Moritz"
  },
  {
    year: 1952,
    maleQuantity: 8,
    femaleQuantity: 3,
    sports: [
      { gender: "F", name: "Figure Skating" },
      { gender: "F", name: "Alpine Skiing" },
      { gender: "F", name: "Cross Country Skiing" },
      { gender: "M", name: "Speed Skating" },
      { gender: "M", name: "Ice Hockey" },
      { gender: "M", name: "Cross Country Skiing" },
      { gender: "M", name: "Bobsleigh" },
      { gender: "M", name: "Alpine Skiing" },
      { gender: "M", name: "Ski Jumping" },
      { gender: "M", name: "Figure Skating" },
      { gender: "M", name: "Nordic Combined" }
    ],
    city: "Oslo"
  },
  {
    year: 1956,
    maleQuantity: 8,
    femaleQuantity: 3,
    sports: [
      { gender: "F", name: "Figure Skating" },
      { gender: "F", name: "Alpine Skiing" },
      { gender: "F", name: "Cross Country Skiing" },
      { gender: "M", name: "Bobsleigh" },
      { gender: "M", name: "Ice Hockey" },
      { gender: "M", name: "Cross Country Skiing" },
      { gender: "M", name: "Figure Skating" },
      { gender: "M", name: "Speed Skating" },
      { gender: "M", name: "Nordic Combined" },
      { gender: "M", name: "Alpine Skiing" },
      { gender: "M", name: "Ski Jumping" }
    ],
    city: "Cortina d'Ampezzo"
  },
  {
    year: 1960,
    maleQuantity: 8,
    femaleQuantity: 4,
    sports: [
      { gender: "F", name: "Speed Skating" },
      { gender: "F", name: "Alpine Skiing" },
      { gender: "F", name: "Figure Skating" },
      { gender: "F", name: "Cross Country Skiing" },
      { gender: "M", name: "Speed Skating" },
      { gender: "M", name: "Cross Country Skiing" },
      { gender: "M", name: "Ice Hockey" },
      { gender: "M", name: "Figure Skating" },
      { gender: "M", name: "Alpine Skiing" },
      { gender: "M", name: "Nordic Combined" },
      { gender: "M", name: "Ski Jumping" },
      { gender: "M", name: "Biathlon" }
    ],
    city: "Squaw Valley"
  },
  {
    year: 1964,
    maleQuantity: 10,
    femaleQuantity: 5,
    sports: [
      { gender: "F", name: "Figure Skating" },
      { gender: "F", name: "Cross Country Skiing" },
      { gender: "F", name: "Luge" },
      { gender: "F", name: "Alpine Skiing" },
      { gender: "F", name: "Speed Skating" },
      { gender: "M", name: "Ice Hockey" },
      { gender: "M", name: "Figure Skating" },
      { gender: "M", name: "Bobsleigh" },
      { gender: "M", name: "Speed Skating" },
      { gender: "M", name: "Cross Country Skiing" },
      { gender: "M", name: "Luge" },
      { gender: "M", name: "Alpine Skiing" },
      { gender: "M", name: "Ski Jumping" },
      { gender: "M", name: "Biathlon" },
      { gender: "M", name: "Nordic Combined" }
    ],
    city: "Innsbruck"
  },
  {
    year: 1968,
    maleQuantity: 10,
    femaleQuantity: 5,
    sports: [
      { gender: "F", name: "Cross Country Skiing" },
      { gender: "F", name: "Speed Skating" },
      { gender: "F", name: "Figure Skating" },
      { gender: "F", name: "Alpine Skiing" },
      { gender: "F", name: "Luge" },
      { gender: "M", name: "Ice Hockey" },
      { gender: "M", name: "Cross Country Skiing" },
      { gender: "M", name: "Bobsleigh" },
      { gender: "M", name: "Biathlon" },
      { gender: "M", name: "Ski Jumping" },
      { gender: "M", name: "Luge" },
      { gender: "M", name: "Figure Skating" },
      { gender: "M", name: "Alpine Skiing" },
      { gender: "M", name: "Speed Skating" },
      { gender: "M", name: "Nordic Combined" }
    ],
    city: "Grenoble"
  },
  {
    year: 1972,
    maleQuantity: 10,
    femaleQuantity: 5,
    sports: [
      { gender: "F", name: "Cross Country Skiing" },
      { gender: "F", name: "Speed Skating" },
      { gender: "F", name: "Alpine Skiing" },
      { gender: "F", name: "Figure Skating" },
      { gender: "F", name: "Luge" },
      { gender: "M", name: "Ice Hockey" },
      { gender: "M", name: "Ski Jumping" },
      { gender: "M", name: "Biathlon" },
      { gender: "M", name: "Bobsleigh" },
      { gender: "M", name: "Luge" },
      { gender: "M", name: "Speed Skating" },
      { gender: "M", name: "Cross Country Skiing" },
      { gender: "M", name: "Alpine Skiing" },
      { gender: "M", name: "Figure Skating" },
      { gender: "M", name: "Nordic Combined" }
    ],
    city: "Sapporo"
  },
  {
    year: 1976,
    maleQuantity: 10,
    femaleQuantity: 5,
    sports: [
      { gender: "F", name: "Cross Country Skiing" },
      { gender: "F", name: "Speed Skating" },
      { gender: "F", name: "Figure Skating" },
      { gender: "F", name: "Alpine Skiing" },
      { gender: "F", name: "Luge" },
      { gender: "M", name: "Ice Hockey" },
      { gender: "M", name: "Ski Jumping" },
      { gender: "M", name: "Bobsleigh" },
      { gender: "M", name: "Cross Country Skiing" },
      { gender: "M", name: "Biathlon" },
      { gender: "M", name: "Luge" },
      { gender: "M", name: "Figure Skating" },
      { gender: "M", name: "Speed Skating" },
      { gender: "M", name: "Alpine Skiing" },
      { gender: "M", name: "Nordic Combined" }
    ],
    city: "Innsbruck"
  },
  {
    year: 1980,
    maleQuantity: 10,
    femaleQuantity: 5,
    sports: [
      { gender: "F", name: "Speed Skating" },
      { gender: "F", name: "Luge" },
      { gender: "F", name: "Cross Country Skiing" },
      { gender: "F", name: "Figure Skating" },
      { gender: "F", name: "Alpine Skiing" },
      { gender: "M", name: "Ice Hockey" },
      { gender: "M", name: "Biathlon" },
      { gender: "M", name: "Speed Skating" },
      { gender: "M", name: "Cross Country Skiing" },
      { gender: "M", name: "Bobsleigh" },
      { gender: "M", name: "Figure Skating" },
      { gender: "M", name: "Luge" },
      { gender: "M", name: "Ski Jumping" },
      { gender: "M", name: "Alpine Skiing" },
      { gender: "M", name: "Nordic Combined" }
    ],
    city: "Lake Placid"
  },
  {
    year: 1984,
    maleQuantity: 10,
    femaleQuantity: 5,
    sports: [
      { gender: "F", name: "Alpine Skiing" },
      { gender: "F", name: "Cross Country Skiing" },
      { gender: "F", name: "Figure Skating" },
      { gender: "F", name: "Speed Skating" },
      { gender: "F", name: "Luge" },
      { gender: "M", name: "Ice Hockey" },
      { gender: "M", name: "Bobsleigh" },
      { gender: "M", name: "Biathlon" },
      { gender: "M", name: "Cross Country Skiing" },
      { gender: "M", name: "Luge" },
      { gender: "M", name: "Speed Skating" },
      { gender: "M", name: "Alpine Skiing" },
      { gender: "M", name: "Figure Skating" },
      { gender: "M", name: "Nordic Combined" },
      { gender: "M", name: "Ski Jumping" }
    ],
    city: "Sarajevo"
  },
  {
    year: 1988,
    maleQuantity: 10,
    femaleQuantity: 5,
    sports: [
      { gender: "F", name: "Figure Skating" },
      { gender: "F", name: "Speed Skating" },
      { gender: "F", name: "Cross Country Skiing" },
      { gender: "F", name: "Alpine Skiing" },
      { gender: "F", name: "Luge" },
      { gender: "M", name: "Alpine Skiing" },
      { gender: "M", name: "Ice Hockey" },
      { gender: "M", name: "Biathlon" },
      { gender: "M", name: "Nordic Combined" },
      { gender: "M", name: "Luge" },
      { gender: "M", name: "Cross Country Skiing" },
      { gender: "M", name: "Figure Skating" },
      { gender: "M", name: "Ski Jumping" },
      { gender: "M", name: "Bobsleigh" },
      { gender: "M", name: "Speed Skating" }
    ],
    city: "Calgary"
  },
  {
    year: 1992,
    maleQuantity: 12,
    femaleQuantity: 8,
    sports: [
      { gender: "F", name: "Short Track Speed Skating" },
      { gender: "F", name: "Figure Skating" },
      { gender: "F", name: "Biathlon" },
      { gender: "F", name: "Cross Country Skiing" },
      { gender: "F", name: "Speed Skating" },
      { gender: "F", name: "Alpine Skiing" },
      { gender: "F", name: "Luge" },
      { gender: "F", name: "Freestyle Skiing" },
      { gender: "M", name: "Alpine Skiing" },
      { gender: "M", name: "Bobsleigh" },
      { gender: "M", name: "Short Track Speed Skating" },
      { gender: "M", name: "Cross Country Skiing" },
      { gender: "M", name: "Freestyle Skiing" },
      { gender: "M", name: "Biathlon" },
      { gender: "M", name: "Nordic Combined" },
      { gender: "M", name: "Ice Hockey" },
      { gender: "M", name: "Figure Skating" },
      { gender: "M", name: "Luge" },
      { gender: "M", name: "Ski Jumping" },
      { gender: "M", name: "Speed Skating" }
    ],
    city: "Albertville"
  },
  {
    year: 1994,
    maleQuantity: 12,
    femaleQuantity: 8,
    sports: [
      { gender: "F", name: "Speed Skating" },
      { gender: "F", name: "Figure Skating" },
      { gender: "F", name: "Biathlon" },
      { gender: "F", name: "Cross Country Skiing" },
      { gender: "F", name: "Short Track Speed Skating" },
      { gender: "F", name: "Freestyle Skiing" },
      { gender: "F", name: "Alpine Skiing" },
      { gender: "F", name: "Luge" },
      { gender: "M", name: "Alpine Skiing" },
      { gender: "M", name: "Nordic Combined" },
      { gender: "M", name: "Bobsleigh" },
      { gender: "M", name: "Ice Hockey" },
      { gender: "M", name: "Cross Country Skiing" },
      { gender: "M", name: "Biathlon" },
      { gender: "M", name: "Short Track Speed Skating" },
      { gender: "M", name: "Luge" },
      { gender: "M", name: "Freestyle Skiing" },
      { gender: "M", name: "Ski Jumping" },
      { gender: "M", name: "Figure Skating" },
      { gender: "M", name: "Speed Skating" }
    ],
    city: "Lillehammer"
  },
  {
    year: 1998,
    maleQuantity: 14,
    femaleQuantity: 11,
    sports: [
      { gender: "F", name: "Biathlon" },
      { gender: "F", name: "Short Track Speed Skating" },
      { gender: "F", name: "Figure Skating" },
      { gender: "F", name: "Speed Skating" },
      { gender: "F", name: "Ice Hockey" },
      { gender: "F", name: "Cross Country Skiing" },
      { gender: "F", name: "Curling" },
      { gender: "F", name: "Freestyle Skiing" },
      { gender: "F", name: "Alpine Skiing" },
      { gender: "F", name: "Snowboarding" },
      { gender: "F", name: "Luge" },
      { gender: "M", name: "Cross Country Skiing" },
      { gender: "M", name: "Short Track Speed Skating" },
      { gender: "M", name: "Curling" },
      { gender: "M", name: "Biathlon" },
      { gender: "M", name: "Bobsleigh" },
      { gender: "M", name: "Nordic Combined" },
      { gender: "M", name: "Luge" },
      { gender: "M", name: "Ice Hockey" },
      { gender: "M", name: "Freestyle Skiing" },
      { gender: "M", name: "Speed Skating" },
      { gender: "M", name: "Alpine Skiing" },
      { gender: "M", name: "Figure Skating" },
      { gender: "M", name: "Snowboarding" },
      { gender: "M", name: "Ski Jumping" }
    ],
    city: "Nagano"
  },
  {
    year: 2002,
    maleQuantity: 15,
    femaleQuantity: 13,
    sports: [
      { gender: "F", name: "Ice Hockey" },
      { gender: "F", name: "Biathlon" },
      { gender: "F", name: "Cross Country Skiing" },
      { gender: "F", name: "Figure Skating" },
      { gender: "F", name: "Freestyle Skiing" },
      { gender: "F", name: "Bobsleigh" },
      { gender: "F", name: "Curling" },
      { gender: "F", name: "Snowboarding" },
      { gender: "F", name: "Alpine Skiing" },
      { gender: "F", name: "Short Track Speed Skating" },
      { gender: "F", name: "Skeleton" },
      { gender: "F", name: "Speed Skating" },
      { gender: "F", name: "Luge" },
      { gender: "M", name: "Alpine Skiing" },
      { gender: "M", name: "Nordic Combined" },
      { gender: "M", name: "Ice Hockey" },
      { gender: "M", name: "Ski Jumping" },
      { gender: "M", name: "Cross Country Skiing" },
      { gender: "M", name: "Short Track Speed Skating" },
      { gender: "M", name: "Bobsleigh" },
      { gender: "M", name: "Biathlon" },
      { gender: "M", name: "Figure Skating" },
      { gender: "M", name: "Curling" },
      { gender: "M", name: "Speed Skating" },
      { gender: "M", name: "Freestyle Skiing" },
      { gender: "M", name: "Luge" },
      { gender: "M", name: "Snowboarding" },
      { gender: "M", name: "Skeleton" }
    ],
    city: "Salt Lake City"
  },
  {
    year: 2006,
    maleQuantity: 15,
    femaleQuantity: 13,
    sports: [
      { gender: "F", name: "Speed Skating" },
      { gender: "F", name: "Ice Hockey" },
      { gender: "F", name: "Biathlon" },
      { gender: "F", name: "Cross Country Skiing" },
      { gender: "F", name: "Figure Skating" },
      { gender: "F", name: "Curling" },
      { gender: "F", name: "Snowboarding" },
      { gender: "F", name: "Short Track Speed Skating" },
      { gender: "F", name: "Freestyle Skiing" },
      { gender: "F", name: "Alpine Skiing" },
      { gender: "F", name: "Bobsleigh" },
      { gender: "F", name: "Skeleton" },
      { gender: "F", name: "Luge" },
      { gender: "M", name: "Alpine Skiing" },
      { gender: "M", name: "Nordic Combined" },
      { gender: "M", name: "Curling" },
      { gender: "M", name: "Figure Skating" },
      { gender: "M", name: "Ski Jumping" },
      { gender: "M", name: "Ice Hockey" },
      { gender: "M", name: "Cross Country Skiing" },
      { gender: "M", name: "Short Track Speed Skating" },
      { gender: "M", name: "Biathlon" },
      { gender: "M", name: "Speed Skating" },
      { gender: "M", name: "Bobsleigh" },
      { gender: "M", name: "Freestyle Skiing" },
      { gender: "M", name: "Snowboarding" },
      { gender: "M", name: "Luge" },
      { gender: "M", name: "Skeleton" }
    ],
    city: "Torino"
  },
  {
    year: 2010,
    maleQuantity: 15,
    femaleQuantity: 13,
    sports: [
      { gender: "F", name: "Ice Hockey" },
      { gender: "F", name: "Speed Skating" },
      { gender: "F", name: "Snowboarding" },
      { gender: "F", name: "Figure Skating" },
      { gender: "F", name: "Freestyle Skiing" },
      { gender: "F", name: "Biathlon" },
      { gender: "F", name: "Curling" },
      { gender: "F", name: "Short Track Speed Skating" },
      { gender: "F", name: "Cross Country Skiing" },
      { gender: "F", name: "Bobsleigh" },
      { gender: "F", name: "Alpine Skiing" },
      { gender: "F", name: "Luge" },
      { gender: "F", name: "Skeleton" },
      { gender: "M", name: "Bobsleigh" },
      { gender: "M", name: "Ski Jumping" },
      { gender: "M", name: "Snowboarding" },
      { gender: "M", name: "Cross Country Skiing" },
      { gender: "M", name: "Ice Hockey" },
      { gender: "M", name: "Short Track Speed Skating" },
      { gender: "M", name: "Freestyle Skiing" },
      { gender: "M", name: "Biathlon" },
      { gender: "M", name: "Speed Skating" },
      { gender: "M", name: "Nordic Combined" },
      { gender: "M", name: "Alpine Skiing" },
      { gender: "M", name: "Skeleton" },
      { gender: "M", name: "Curling" },
      { gender: "M", name: "Luge" },
      { gender: "M", name: "Figure Skating" }
    ],
    city: "Vancouver"
  },
  {
    year: 2014,
    maleQuantity: 15,
    femaleQuantity: 14,
    sports: [
      { gender: "F", name: "Curling" },
      { gender: "F", name: "Ice Hockey" },
      { gender: "F", name: "Snowboarding" },
      { gender: "F", name: "Biathlon" },
      { gender: "F", name: "Cross Country Skiing" },
      { gender: "F", name: "Figure Skating" },
      { gender: "F", name: "Speed Skating" },
      { gender: "F", name: "Freestyle Skiing" },
      { gender: "F", name: "Short Track Speed Skating" },
      { gender: "F", name: "Bobsleigh" },
      { gender: "F", name: "Alpine Skiing" },
      { gender: "F", name: "Luge" },
      { gender: "F", name: "Ski Jumping" },
      { gender: "F", name: "Skeleton" },
      { gender: "M", name: "Ice Hockey" },
      { gender: "M", name: "Figure Skating" },
      { gender: "M", name: "Short Track Speed Skating" },
      { gender: "M", name: "Curling" },
      { gender: "M", name: "Skeleton" },
      { gender: "M", name: "Luge" },
      { gender: "M", name: "Ski Jumping" },
      { gender: "M", name: "Bobsleigh" },
      { gender: "M", name: "Biathlon" },
      { gender: "M", name: "Speed Skating" },
      { gender: "M", name: "Cross Country Skiing" },
      { gender: "M", name: "Nordic Combined" },
      { gender: "M", name: "Freestyle Skiing" },
      { gender: "M", name: "Snowboarding" },
      { gender: "M", name: "Alpine Skiing" }
    ],
    city: "Sochi"
  },
  {
    year: 2018,
    maleQuantity: 15,
    femaleQuantity: 14,
    sports: [
      { gender: "F", name: "Curling" },
      { gender: "F", name: "Ice Hockey" },
      { gender: "F", name: "Snowboarding" },
      { gender: "F", name: "Biathlon" },
      { gender: "F", name: "Cross Country Skiing" },
      { gender: "F", name: "Figure Skating" },
      { gender: "F", name: "Speed Skating" },
      { gender: "F", name: "Freestyle Skiing" },
      { gender: "F", name: "Short Track Speed Skating" },
      { gender: "F", name: "Bobsleigh" },
      { gender: "F", name: "Alpine Skiing" },
      { gender: "F", name: "Luge" },
      { gender: "F", name: "Ski Jumping" },
      { gender: "F", name: "Skeleton" },
      { gender: "M", name: "Ice Hockey" },
      { gender: "M", name: "Figure Skating" },
      { gender: "M", name: "Short Track Speed Skating" },
      { gender: "M", name: "Curling" },
      { gender: "M", name: "Skeleton" },
      { gender: "M", name: "Luge" },
      { gender: "M", name: "Ski Jumping" },
      { gender: "M", name: "Bobsleigh" },
      { gender: "M", name: "Biathlon" },
      { gender: "M", name: "Speed Skating" },
      { gender: "M", name: "Cross Country Skiing" },
      { gender: "M", name: "Nordic Combined" },
      { gender: "M", name: "Freestyle Skiing" },
      { gender: "M", name: "Snowboarding" },
      { gender: "M", name: "Alpine Skiing" }
    ],
    city: "PyeongChang"
  },
  {
    year: 2022,
    maleQuantity: 15,
    femaleQuantity: 14,
    sports: [
      { gender: "F", name: "Curling" },
      { gender: "F", name: "Ice Hockey" },
      { gender: "F", name: "Snowboarding" },
      { gender: "F", name: "Biathlon" },
      { gender: "F", name: "Cross Country Skiing" },
      { gender: "F", name: "Figure Skating" },
      { gender: "F", name: "Speed Skating" },
      { gender: "F", name: "Freestyle Skiing" },
      { gender: "F", name: "Short Track Speed Skating" },
      { gender: "F", name: "Bobsleigh" },
      { gender: "F", name: "Alpine Skiing" },
      { gender: "F", name: "Luge" },
      { gender: "F", name: "Ski Jumping" },
      { gender: "F", name: "Skeleton" },
      { gender: "M", name: "Ice Hockey" },
      { gender: "M", name: "Figure Skating" },
      { gender: "M", name: "Short Track Speed Skating" },
      { gender: "M", name: "Curling" },
      { gender: "M", name: "Skeleton" },
      { gender: "M", name: "Luge" },
      { gender: "M", name: "Ski Jumping" },
      { gender: "M", name: "Bobsleigh" },
      { gender: "M", name: "Biathlon" },
      { gender: "M", name: "Speed Skating" },
      { gender: "M", name: "Cross Country Skiing" },
      { gender: "M", name: "Nordic Combined" },
      { gender: "M", name: "Freestyle Skiing" },
      { gender: "M", name: "Snowboarding" },
      { gender: "M", name: "Alpine Skiing" }
    ],
    city: "Beijing"
  }
];
