export const data = [
  {
    country: "2227974-0",
    nombre: "Manuel",
    apellidos: "Cárdenas",
    sexo: "Femenino",
    end_date: "2007-05-14",
    fecha_ingreso_grupo: "2013-08-20",
    fecha_nacimiento: "1974-01-15",
    fecha_renuncia: null,
    tipo_renuncia: null,
    division: "Gerencia General",
    gerencia: "Activos Irreg y Recuperaciones",
    periodo: "11-2018",
    piramide: "Administrativos",
    tipo_contrato: "Indefinido",
    nombre_empresa: "Santander",
    tipo_renta: "Renta Variable",
    cargo: "Administrativos",
    estado_civil: "Separado",
    num_hijos: 4,
    tipo_area: "Apoyo y Estructura",
    es_plantilla: true
  },
  {
    country: "408015-0",
    nombre: "Manuel",
    apellidos: "Puga",
    sexo: "Femenino",
    end_date: "2007-05-14",
    fecha_ingreso_grupo: "2017-09-12",
    fecha_nacimiento: "1974-01-15",
    fecha_renuncia: null,
    tipo_renuncia: null,
    division: "Banca Empresas e Intituciones",
    gerencia: "Activos Irreg y Recuperaciones",
    periodo: "11-2018",
    piramide: "Administrativos",
    tipo_contrato: "Indefinido",
    nombre_empresa: "Leniolabs",
    tipo_renta: "Renta Variable",
    cargo: "Jefaturas y Profesionales Sr",
    estado_civil: "Casado(a)",
    num_hijos: 3,
    tipo_area: "Apoyo y Estructura",
    es_plantilla: true
  },
  {
    country: "9171031-0",
    nombre: "Matilde",
    apellidos: "Navarrete",
    sexo: "Masculino",
    end_date: "2007-05-14",
    fecha_ingreso_grupo: "2014-10-31",
    fecha_nacimiento: "1974-01-15",
    fecha_renuncia: null,
    tipo_renuncia: null,
    division: "Comercial",
    gerencia: "Activos Irreg y Recuperaciones",
    periodo: "11-2018",
    piramide: "Administrativos",
    tipo_contrato: "Indefinido",
    nombre_empresa: "Santander",
    tipo_renta: "Renta Variable",
    cargo: "Profesionales y Tecnicos",
    estado_civil: "Casado(a)",
    num_hijos: 4,
    tipo_area: "Apoyo y Estructura",
    es_plantilla: true
  },
  {
    country: "5910098-0",
    nombre: "Marta",
    apellidos: "Jaime",
    sexo: "Masculino",
    end_date: "2007-05-14",
    fecha_ingreso_grupo: "2015-05-19",
    fecha_nacimiento: "1974-01-15",
    fecha_renuncia: null,
    tipo_renuncia: null,
    division: "Personas y Comunicación",
    gerencia: "Activos Irreg y Recuperaciones",
    periodo: "11-2018",
    piramide: "Administrativos",
    tipo_contrato: "Indefinido",
    nombre_empresa: "Leniolabs",
    tipo_renta: "Renta Variable",
    cargo: "Jefaturas y Profesionales Sr",
    estado_civil: "Casado(a)",
    num_hijos: 3,
    tipo_area: "Apoyo y Estructura",
    es_plantilla: true
  },
  {
    country: "462897-0",
    nombre: "Lorena",
    apellidos: "Corral",
    sexo: "Masculino",
    end_date: "2007-05-14",
    fecha_ingreso_grupo: "2018-09-13",
    fecha_nacimiento: "1974-01-15",
    fecha_renuncia: null,
    tipo_renuncia: null,
    division: "Auditoria",
    gerencia: "Activos Irreg y Recuperaciones",
    periodo: "11-2018",
    piramide: "Administrativos",
    tipo_contrato: "Indefinido",
    nombre_empresa: "Leniolabs",
    tipo_renta: "Renta Variable",
    cargo: "Administrativos",
    estado_civil: "Divorciado",
    num_hijos: 1,
    tipo_area: "Apoyo y Estructura",
    es_plantilla: true
  },
  {
    country: "5697253-0",
    nombre: "Maica",
    apellidos: "Vázquez",
    sexo: "Masculino",
    end_date: "2007-05-14",
    fecha_ingreso_grupo: "2017-05-03",
    fecha_nacimiento: "1974-01-15",
    fecha_renuncia: null,
    tipo_renuncia: null,
    division: "Financiera",
    gerencia: "Activos Irreg y Recuperaciones",
    periodo: "11-2018",
    piramide: "Administrativos",
    tipo_contrato: "Indefinido",
    nombre_empresa: "Santander",
    tipo_renta: "Renta Variable",
    cargo: "Profesionales y Tecnicos",
    estado_civil: "Separado",
    num_hijos: 2,
    tipo_area: "Apoyo y Estructura",
    es_plantilla: true
  },
  {
    country: "8027584-0",
    nombre: "Anni",
    apellidos: "Escalante",
    sexo: "Masculino",
    end_date: "2007-05-14",
    fecha_ingreso_grupo: "2017-05-09",
    fecha_nacimiento: "1974-01-15",
    fecha_renuncia: null,
    tipo_renuncia: null,
    division: "Personas y Comunicación",
    gerencia: "Activos Irreg y Recuperaciones",
    periodo: "11-2018",
    piramide: "Administrativos",
    tipo_contrato: "Indefinido",
    nombre_empresa: "Leniolabs",
    tipo_renta: "Renta Variable",
    cargo: "Administrativos",
    estado_civil: "Casado(a)",
    num_hijos: 4,
    tipo_area: "Apoyo y Estructura",
    es_plantilla: true
  },
  {
    country: "7208842-0",
    nombre: "Lorena",
    apellidos: "Bravo",
    sexo: "Masculino",
    end_date: "2007-05-14",
    fecha_ingreso_grupo: "2016-08-10",
    fecha_nacimiento: "1974-01-15",
    fecha_renuncia: null,
    tipo_renuncia: null,
    division: "Comercial",
    gerencia: "Activos Irreg y Recuperaciones",
    periodo: "11-2018",
    piramide: "Administrativos",
    tipo_contrato: "Indefinido",
    nombre_empresa: "Santander",
    tipo_renta: "Renta Variable",
    cargo: "Jefaturas y Profesionales Sr",
    estado_civil: "Viudo(a)",
    num_hijos: 3,
    tipo_area: "Apoyo y Estructura",
    es_plantilla: true
  },
  {
    country: "7843241-0",
    nombre: "Jordi",
    apellidos: "Bustos",
    sexo: "Femenino",
    end_date: "2007-05-14",
    fecha_ingreso_grupo: "2018-01-17",
    fecha_nacimiento: "1974-01-15",
    fecha_renuncia: null,
    tipo_renuncia: null,
    division: "Tecnología y Operaciones",
    gerencia: "Activos Irreg y Recuperaciones",
    periodo: "11-2018",
    piramide: "Administrativos",
    tipo_contrato: "Indefinido",
    nombre_empresa: "Leniolabs",
    tipo_renta: "Renta Variable",
    cargo: "Administrativos",
    estado_civil: "Conviviente Civil",
    num_hijos: 1,
    tipo_area: "Apoyo y Estructura",
    es_plantilla: true
  },
  {
    country: "3457942-0",
    nombre: "Laura",
    apellidos: "Valdez",
    sexo: "Masculino",
    end_date: "2007-05-14",
    fecha_ingreso_grupo: "2013-11-02",
    fecha_nacimiento: "1974-01-15",
    fecha_renuncia: null,
    tipo_renuncia: null,
    division: "Comercial",
    gerencia: "Activos Irreg y Recuperaciones",
    periodo: "11-2018",
    piramide: "Administrativos",
    tipo_contrato: "Indefinido",
    nombre_empresa: "Santander",
    tipo_renta: "Renta Variable",
    cargo: "Administrativos",
    estado_civil: "Conviviente Civil",
    num_hijos: 2,
    tipo_area: "Apoyo y Estructura",
    es_plantilla: true
  },
  {
    country: "2535277-0",
    nombre: "Marta",
    apellidos: "Valentín",
    sexo: "Masculino",
    end_date: "2007-05-14",
    fecha_ingreso_grupo: "2011-07-10",
    fecha_nacimiento: "1974-01-15",
    fecha_renuncia: null,
    tipo_renuncia: null,
    division: "Personas y Comunicación",
    gerencia: "Activos Irreg y Recuperaciones",
    periodo: "11-2018",
    piramide: "Administrativos",
    tipo_contrato: "Indefinido",
    nombre_empresa: "Leniolabs",
    tipo_renta: "Renta Variable",
    cargo: "Administrativos",
    estado_civil: "Separado",
    num_hijos: 1,
    tipo_area: "Apoyo y Estructura",
    es_plantilla: true
  },
  {
    country: "888836-0",
    nombre: "Ana",
    apellidos: "Saldivar",
    sexo: "Masculino",
    end_date: "2007-05-14",
    fecha_ingreso_grupo: "2017-11-16",
    fecha_nacimiento: "1974-01-15",
    fecha_renuncia: null,
    tipo_renuncia: null,
    division: "Banca Empresas e Intituciones",
    gerencia: "Activos Irreg y Recuperaciones",
    periodo: "11-2018",
    piramide: "Administrativos",
    tipo_contrato: "Indefinido",
    nombre_empresa: "Santander",
    tipo_renta: "Renta Variable",
    cargo: "Profesionales y Tecnicos",
    estado_civil: "Soltero(a)",
    num_hijos: 0,
    tipo_area: "Apoyo y Estructura",
    es_plantilla: true
  },
  {
    country: "1096369-0",
    nombre: "Andrea",
    apellidos: "Olivera",
    sexo: "Masculino",
    end_date: "2007-05-14",
    fecha_ingreso_grupo: "2016-12-07",
    fecha_nacimiento: "1974-01-15",
    fecha_renuncia: null,
    tipo_renuncia: null,
    division: "Jurídica ",
    gerencia: "Activos Irreg y Recuperaciones",
    periodo: "11-2018",
    piramide: "Administrativos",
    tipo_contrato: "Indefinido",
    nombre_empresa: "Leniolabs",
    tipo_renta: "Renta Variable",
    cargo: "Profesionales y Tecnicos",
    estado_civil: "Casado(a)",
    num_hijos: 2,
    tipo_area: "Apoyo y Estructura",
    es_plantilla: true
  },
  {
    country: "8913752-0",
    nombre: "Miguel",
    apellidos: "Piña",
    sexo: "Femenino",
    end_date: "2007-05-14",
    fecha_ingreso_grupo: "2019-12-26",
    fecha_nacimiento: "1974-01-15",
    fecha_renuncia: null,
    tipo_renuncia: null,
    division: "Jurídica ",
    gerencia: "Activos Irreg y Recuperaciones",
    periodo: "11-2018",
    piramide: "Administrativos",
    tipo_contrato: "Indefinido",
    nombre_empresa: "Santander",
    tipo_renta: "Renta Variable",
    cargo: "Administrativos",
    estado_civil: "Soltero(a)",
    num_hijos: 3,
    tipo_area: "Apoyo y Estructura",
    es_plantilla: true
  },
  {
    country: "5785614-0",
    nombre: "Manuel",
    apellidos: "Peralta",
    sexo: "Femenino",
    end_date: "2007-05-14",
    fecha_ingreso_grupo: "2013-01-31",
    fecha_nacimiento: "1974-01-15",
    fecha_renuncia: null,
    tipo_renuncia: null,
    division: "Jurídica ",
    gerencia: "Activos Irreg y Recuperaciones",
    periodo: "11-2018",
    piramide: "Administrativos",
    tipo_contrato: "Indefinido",
    nombre_empresa: "Santander",
    tipo_renta: "Renta Variable",
    cargo: "Jefaturas y Profesionales Sr",
    estado_civil: "Soltero(a)",
    num_hijos: 1,
    tipo_area: "Apoyo y Estructura",
    es_plantilla: true
  },
  {
    country: "9634087-0",
    nombre: "Carles",
    apellidos: "Loera",
    sexo: "Femenino",
    end_date: "2007-05-14",
    fecha_ingreso_grupo: "2011-08-11",
    fecha_nacimiento: "1974-01-15",
    fecha_renuncia: null,
    tipo_renuncia: null,
    division: "Clientes y Calidad",
    gerencia: "Activos Irreg y Recuperaciones",
    periodo: "11-2018",
    piramide: "Administrativos",
    tipo_contrato: "Indefinido",
    nombre_empresa: "Leniolabs",
    tipo_renta: "Renta Variable",
    cargo: "Jefaturas y Profesionales Sr",
    estado_civil: "Separado",
    num_hijos: 4,
    tipo_area: "Apoyo y Estructura",
    es_plantilla: true
  },
  {
    country: "4144536-0",
    nombre: "Jennifer",
    apellidos: "Cazares",
    sexo: "Masculino",
    end_date: "2007-05-14",
    fecha_ingreso_grupo: "2010-08-20",
    fecha_nacimiento: "1974-01-15",
    fecha_renuncia: null,
    tipo_renuncia: null,
    division: "Financiera",
    gerencia: "Activos Irreg y Recuperaciones",
    periodo: "11-2018",
    piramide: "Administrativos",
    tipo_contrato: "Indefinido",
    nombre_empresa: "Santander",
    tipo_renta: "Renta Variable",
    cargo: "Profesionales y Tecnicos",
    estado_civil: "Soltero(a)",
    num_hijos: 2,
    tipo_area: "Apoyo y Estructura",
    es_plantilla: true
  },
  {
    country: "1692675-0",
    nombre: "Iván",
    apellidos: "Pizarro",
    sexo: "Femenino",
    end_date: "2007-05-14",
    fecha_ingreso_grupo: "2012-04-16",
    fecha_nacimiento: "1974-01-15",
    fecha_renuncia: null,
    tipo_renuncia: null,
    division: "Clientes y Calidad",
    gerencia: "Activos Irreg y Recuperaciones",
    periodo: "11-2018",
    piramide: "Administrativos",
    tipo_contrato: "Indefinido",
    nombre_empresa: "Leniolabs",
    tipo_renta: "Renta Variable",
    cargo: "Profesionales y Tecnicos",
    estado_civil: "Divorciado",
    num_hijos: 2,
    tipo_area: "Apoyo y Estructura",
    es_plantilla: true
  },
  {
    country: "2217435-0",
    nombre: "Jorge",
    apellidos: "Sisneros",
    sexo: "Femenino",
    end_date: "2007-05-14",
    fecha_ingreso_grupo: "2014-12-26",
    fecha_nacimiento: "1974-01-15",
    fecha_renuncia: null,
    tipo_renuncia: null,
    division: "Personas y Comunicación",
    gerencia: "Activos Irreg y Recuperaciones",
    periodo: "11-2018",
    piramide: "Administrativos",
    tipo_contrato: "Indefinido",
    nombre_empresa: "Santander",
    tipo_renta: "Renta Variable",
    cargo: "Profesionales y Tecnicos",
    estado_civil: "Divorciado",
    num_hijos: 0,
    tipo_area: "Apoyo y Estructura",
    es_plantilla: true
  },
  {
    country: "2037963-0",
    nombre: "Laura",
    apellidos: "Tafoya",
    sexo: "Masculino",
    end_date: "2007-05-14",
    fecha_ingreso_grupo: "2015-03-23",
    fecha_nacimiento: "1974-01-15",
    fecha_renuncia: null,
    tipo_renuncia: null,
    division: "Financiera",
    gerencia: "Activos Irreg y Recuperaciones",
    periodo: "11-2018",
    piramide: "Administrativos",
    tipo_contrato: "Indefinido",
    nombre_empresa: "Leniolabs",
    tipo_renta: "Renta Variable",
    cargo: "Profesionales y Tecnicos",
    estado_civil: "Sin Definir",
    num_hijos: 2,
    tipo_area: "Apoyo y Estructura",
    es_plantilla: true
  },
  {
    country: "2591574-0",
    nombre: "Ángel",
    apellidos: "Rincón",
    sexo: "Femenino",
    end_date: "2007-05-14",
    fecha_ingreso_grupo: "2012-11-04",
    fecha_nacimiento: "1974-01-15",
    fecha_renuncia: null,
    tipo_renuncia: null,
    division: "Gerencia General",
    gerencia: "Activos Irreg y Recuperaciones",
    periodo: "11-2018",
    piramide: "Administrativos",
    tipo_contrato: "Indefinido",
    nombre_empresa: "Santander",
    tipo_renta: "Renta Variable",
    cargo: "Administrativos",
    estado_civil: "Soltero(a)",
    num_hijos: 4,
    tipo_area: "Apoyo y Estructura",
    es_plantilla: true
  },
  {
    country: "5037533-0",
    nombre: "Sergi",
    apellidos: "Velasco",
    sexo: "Femenino",
    end_date: "2007-05-14",
    fecha_ingreso_grupo: "2016-08-27",
    fecha_nacimiento: "1974-01-15",
    fecha_renuncia: null,
    tipo_renuncia: null,
    division: "Clientes y Calidad",
    gerencia: "Activos Irreg y Recuperaciones",
    periodo: "11-2018",
    piramide: "Administrativos",
    tipo_contrato: "Indefinido",
    nombre_empresa: "Leniolabs",
    tipo_renta: "Renta Variable",
    cargo: "Gerentes",
    estado_civil: "Conviviente Civil",
    num_hijos: 1,
    tipo_area: "Apoyo y Estructura",
    es_plantilla: true
  },
  {
    country: "7037851-0",
    nombre: "Marta",
    apellidos: "Serna",
    sexo: "Masculino",
    end_date: "2007-05-14",
    fecha_ingreso_grupo: "2011-07-05",
    fecha_nacimiento: "1974-01-15",
    fecha_renuncia: null,
    tipo_renuncia: null,
    division: "Comercial",
    gerencia: "Activos Irreg y Recuperaciones",
    periodo: "11-2018",
    piramide: "Administrativos",
    tipo_contrato: "Indefinido",
    nombre_empresa: "Santander",
    tipo_renta: "Renta Variable",
    cargo: "Administrativos",
    estado_civil: "Conviviente Civil",
    num_hijos: 2,
    tipo_area: "Apoyo y Estructura",
    es_plantilla: true
  },
  {
    country: "6297816-0",
    nombre: "Manuel",
    apellidos: "Alaníz",
    sexo: "Femenino",
    end_date: "2007-05-14",
    fecha_ingreso_grupo: "2011-02-21",
    fecha_nacimiento: "1974-01-15",
    fecha_renuncia: null,
    tipo_renuncia: null,
    division: "Banca Empresas e Intituciones",
    gerencia: "Activos Irreg y Recuperaciones",
    periodo: "11-2018",
    piramide: "Administrativos",
    tipo_contrato: "Indefinido",
    nombre_empresa: "Santander",
    tipo_renta: "Renta Variable",
    cargo: "Jefaturas y Profesionales Sr",
    estado_civil: "Soltero(a)",
    num_hijos: 2,
    tipo_area: "Apoyo y Estructura",
    es_plantilla: true
  },
  {
    country: "5443631-0",
    nombre: "Laura",
    apellidos: "Farías",
    sexo: "Masculino",
    end_date: "2007-05-14",
    fecha_ingreso_grupo: "2012-11-22",
    fecha_nacimiento: "1974-01-15",
    fecha_renuncia: null,
    tipo_renuncia: null,
    division: "Riesgos",
    gerencia: "Activos Irreg y Recuperaciones",
    periodo: "11-2018",
    piramide: "Administrativos",
    tipo_contrato: "Indefinido",
    nombre_empresa: "Leniolabs",
    tipo_renta: "Renta Variable",
    cargo: "Administrativos",
    estado_civil: "Sin Definir",
    num_hijos: 1,
    tipo_area: "Apoyo y Estructura",
    es_plantilla: true
  },
  {
    country: "3369480-0",
    nombre: "Sergi",
    apellidos: "Rojo",
    sexo: "Femenino",
    end_date: "2007-05-14",
    fecha_ingreso_grupo: "2013-02-07",
    fecha_nacimiento: "1974-01-15",
    fecha_renuncia: null,
    tipo_renuncia: null,
    division: "Jurídica ",
    gerencia: "Activos Irreg y Recuperaciones",
    periodo: "11-2018",
    piramide: "Administrativos",
    tipo_contrato: "Indefinido",
    nombre_empresa: "Santander",
    tipo_renta: "Renta Variable",
    cargo: "Profesionales y Tecnicos",
    estado_civil: "Sin Definir",
    num_hijos: 4,
    tipo_area: "Apoyo y Estructura",
    es_plantilla: true
  },
  {
    country: "8406557-0",
    nombre: "Carles",
    apellidos: "Mares",
    sexo: "Femenino",
    end_date: "2007-05-14",
    fecha_ingreso_grupo: "2010-03-03",
    fecha_nacimiento: "1974-01-15",
    fecha_renuncia: null,
    tipo_renuncia: null,
    division: "Financiera",
    gerencia: "Activos Irreg y Recuperaciones",
    periodo: "11-2018",
    piramide: "Administrativos",
    tipo_contrato: "Indefinido",
    nombre_empresa: "Santander",
    tipo_renta: "Renta Variable",
    cargo: "Jefaturas y Profesionales Sr",
    estado_civil: "Casado(a)",
    num_hijos: 1,
    tipo_area: "Apoyo y Estructura",
    es_plantilla: true
  },
  {
    country: "1665676-0",
    nombre: "Ricardo",
    apellidos: "Perales",
    sexo: "Femenino",
    end_date: "2007-05-14",
    fecha_ingreso_grupo: "2013-09-15",
    fecha_nacimiento: "1974-01-15",
    fecha_renuncia: null,
    tipo_renuncia: null,
    division: "Banca Empresas e Intituciones",
    gerencia: "Activos Irreg y Recuperaciones",
    periodo: "11-2018",
    piramide: "Administrativos",
    tipo_contrato: "Indefinido",
    nombre_empresa: "Santander",
    tipo_renta: "Renta Variable",
    cargo: "Profesionales y Tecnicos",
    estado_civil: "Casado(a)",
    num_hijos: 0,
    tipo_area: "Apoyo y Estructura",
    es_plantilla: true
  },
  {
    country: "4657821-0",
    nombre: "Rubén",
    apellidos: "Menéndez",
    sexo: "Femenino",
    end_date: "2007-05-14",
    fecha_ingreso_grupo: "2019-09-10",
    fecha_nacimiento: "1974-01-15",
    fecha_renuncia: null,
    tipo_renuncia: null,
    division: "Personas y Comunicación",
    gerencia: "Activos Irreg y Recuperaciones",
    periodo: "11-2018",
    piramide: "Administrativos",
    tipo_contrato: "Indefinido",
    nombre_empresa: "Santander",
    tipo_renta: "Renta Variable",
    cargo: "Profesionales y Tecnicos",
    estado_civil: "Divorciado",
    num_hijos: 0,
    tipo_area: "Apoyo y Estructura",
    es_plantilla: true
  },
  {
    country: "116600-0",
    nombre: "Daniel",
    apellidos: "Prado",
    sexo: "Femenino",
    end_date: "2007-05-14",
    fecha_ingreso_grupo: "2015-03-29",
    fecha_nacimiento: "1974-01-15",
    fecha_renuncia: null,
    tipo_renuncia: null,
    division: "Financiera",
    gerencia: "Activos Irreg y Recuperaciones",
    periodo: "11-2018",
    piramide: "Administrativos",
    tipo_contrato: "Indefinido",
    nombre_empresa: "Leniolabs",
    tipo_renta: "Renta Variable",
    cargo: "Gerentes",
    estado_civil: "Divorciado",
    num_hijos: 0,
    tipo_area: "Apoyo y Estructura",
    es_plantilla: true
  },
  {
    country: "9600972-0",
    nombre: "Salvador",
    apellidos: "Carrero",
    sexo: "Femenino",
    end_date: "2007-05-14",
    fecha_ingreso_grupo: "2013-01-06",
    fecha_nacimiento: "1974-01-15",
    fecha_renuncia: null,
    tipo_renuncia: null,
    division: "Clientes y Calidad",
    gerencia: "Activos Irreg y Recuperaciones",
    periodo: "11-2018",
    piramide: "Administrativos",
    tipo_contrato: "Indefinido",
    nombre_empresa: "Santander",
    tipo_renta: "Renta Variable",
    cargo: "Administrativos",
    estado_civil: "Viudo(a)",
    num_hijos: 2,
    tipo_area: "Apoyo y Estructura",
    es_plantilla: true
  },
  {
    country: "8431839-0",
    nombre: "Ángel",
    apellidos: "Esquivel",
    sexo: "Femenino",
    end_date: "2007-05-14",
    fecha_ingreso_grupo: "2016-08-03",
    fecha_nacimiento: "1974-01-15",
    fecha_renuncia: null,
    tipo_renuncia: null,
    division: "Auditoria",
    gerencia: "Activos Irreg y Recuperaciones",
    periodo: "11-2018",
    piramide: "Administrativos",
    tipo_contrato: "Indefinido",
    nombre_empresa: "Leniolabs",
    tipo_renta: "Renta Variable",
    cargo: "Administrativos",
    estado_civil: "Soltero(a)",
    num_hijos: 4,
    tipo_area: "Apoyo y Estructura",
    es_plantilla: true
  },
  {
    country: "9581280-0",
    nombre: "Matilde",
    apellidos: "Abeyta",
    sexo: "Masculino",
    end_date: "2007-05-14",
    fecha_ingreso_grupo: "2015-10-01",
    fecha_nacimiento: "1974-01-15",
    fecha_renuncia: null,
    tipo_renuncia: null,
    division: "Riesgos",
    gerencia: "Activos Irreg y Recuperaciones",
    periodo: "11-2018",
    piramide: "Administrativos",
    tipo_contrato: "Indefinido",
    nombre_empresa: "Santander",
    tipo_renta: "Renta Variable",
    cargo: "Profesionales y Tecnicos",
    estado_civil: "Casado(a)",
    num_hijos: 1,
    tipo_area: "Apoyo y Estructura",
    es_plantilla: true
  },
  {
    country: "9685412-0",
    nombre: "Roser",
    apellidos: "Montero",
    sexo: "Masculino",
    end_date: "2007-05-14",
    fecha_ingreso_grupo: "2011-04-01",
    fecha_nacimiento: "1974-01-15",
    fecha_renuncia: null,
    tipo_renuncia: null,
    division: "Personas y Comunicación",
    gerencia: "Activos Irreg y Recuperaciones",
    periodo: "11-2018",
    piramide: "Administrativos",
    tipo_contrato: "Indefinido",
    nombre_empresa: "Leniolabs",
    tipo_renta: "Renta Variable",
    cargo: "Profesionales y Tecnicos",
    estado_civil: "Conviviente Civil",
    num_hijos: 3,
    tipo_area: "Apoyo y Estructura",
    es_plantilla: true
  },
  {
    country: "5817980-0",
    nombre: "Marta",
    apellidos: "Carrión",
    sexo: "Masculino",
    end_date: "2007-05-14",
    fecha_ingreso_grupo: "2018-04-10",
    fecha_nacimiento: "1974-01-15",
    fecha_renuncia: null,
    tipo_renuncia: null,
    division: "Tecnología y Operaciones",
    gerencia: "Activos Irreg y Recuperaciones",
    periodo: "11-2018",
    piramide: "Administrativos",
    tipo_contrato: "Indefinido",
    nombre_empresa: "Santander",
    tipo_renta: "Renta Variable",
    cargo: "Administrativos",
    estado_civil: "Separado",
    num_hijos: 0,
    tipo_area: "Apoyo y Estructura",
    es_plantilla: true
  },
  {
    country: "2410244-0",
    nombre: "Carles",
    apellidos: "Gaitán",
    sexo: "Femenino",
    end_date: "2007-05-14",
    fecha_ingreso_grupo: "2011-05-28",
    fecha_nacimiento: "1974-01-15",
    fecha_renuncia: null,
    tipo_renuncia: null,
    division: "Financiera",
    gerencia: "Activos Irreg y Recuperaciones",
    periodo: "11-2018",
    piramide: "Administrativos",
    tipo_contrato: "Indefinido",
    nombre_empresa: "Santander",
    tipo_renta: "Renta Variable",
    cargo: "Profesionales y Tecnicos",
    estado_civil: "Casado(a)",
    num_hijos: 0,
    tipo_area: "Apoyo y Estructura",
    es_plantilla: true
  },
  {
    country: "6600723-0",
    nombre: "Marta",
    apellidos: "Rangel",
    sexo: "Masculino",
    end_date: "2007-05-14",
    fecha_ingreso_grupo: "2019-10-24",
    fecha_nacimiento: "1974-01-15",
    fecha_renuncia: null,
    tipo_renuncia: null,
    division: "Tecnología y Operaciones",
    gerencia: "Activos Irreg y Recuperaciones",
    periodo: "11-2018",
    piramide: "Administrativos",
    tipo_contrato: "Indefinido",
    nombre_empresa: "Santander",
    tipo_renta: "Renta Variable",
    cargo: "Profesionales y Tecnicos",
    estado_civil: "Viudo(a)",
    num_hijos: 3,
    tipo_area: "Apoyo y Estructura",
    es_plantilla: true
  },
  {
    country: "9825400-0",
    nombre: "Ana",
    apellidos: "Luna",
    sexo: "Masculino",
    end_date: "2007-05-14",
    fecha_ingreso_grupo: "2016-10-23",
    fecha_nacimiento: "1974-01-15",
    fecha_renuncia: null,
    tipo_renuncia: null,
    division: "Riesgos",
    gerencia: "Activos Irreg y Recuperaciones",
    periodo: "11-2018",
    piramide: "Administrativos",
    tipo_contrato: "Indefinido",
    nombre_empresa: "Leniolabs",
    tipo_renta: "Renta Variable",
    cargo: "Profesionales y Tecnicos",
    estado_civil: "Conviviente Civil",
    num_hijos: 4,
    tipo_area: "Apoyo y Estructura",
    es_plantilla: true
  },
  {
    country: "400279-0",
    nombre: "Matilde",
    apellidos: "Abeyta",
    sexo: "Masculino",
    end_date: "2007-05-14",
    fecha_ingreso_grupo: "2018-03-31",
    fecha_nacimiento: "1974-01-15",
    fecha_renuncia: null,
    tipo_renuncia: null,
    division: "Tecnología y Operaciones",
    gerencia: "Activos Irreg y Recuperaciones",
    periodo: "11-2018",
    piramide: "Administrativos",
    tipo_contrato: "Indefinido",
    nombre_empresa: "Santander",
    tipo_renta: "Renta Variable",
    cargo: "Profesionales y Tecnicos",
    estado_civil: "Separado",
    num_hijos: 3,
    tipo_area: "Apoyo y Estructura",
    es_plantilla: true
  },
  {
    country: "9860985-0",
    nombre: "Matilde",
    apellidos: "Madrid",
    sexo: "Masculino",
    end_date: "2007-05-14",
    fecha_ingreso_grupo: "2017-08-20",
    fecha_nacimiento: "1974-01-15",
    fecha_renuncia: null,
    tipo_renuncia: null,
    division: "Comercial",
    gerencia: "Activos Irreg y Recuperaciones",
    periodo: "11-2018",
    piramide: "Administrativos",
    tipo_contrato: "Indefinido",
    nombre_empresa: "Leniolabs",
    tipo_renta: "Renta Variable",
    cargo: "Profesionales y Tecnicos",
    estado_civil: "Viudo(a)",
    num_hijos: 3,
    tipo_area: "Apoyo y Estructura",
    es_plantilla: true
  },
  {
    country: "7515367-0",
    nombre: "Ana",
    apellidos: "Cortéz",
    sexo: "Masculino",
    end_date: "2007-05-14",
    fecha_ingreso_grupo: "2010-06-14",
    fecha_nacimiento: "1974-01-15",
    fecha_renuncia: null,
    tipo_renuncia: null,
    division: "Clientes y Calidad",
    gerencia: "Activos Irreg y Recuperaciones",
    periodo: "11-2018",
    piramide: "Administrativos",
    tipo_contrato: "Indefinido",
    nombre_empresa: "Leniolabs",
    tipo_renta: "Renta Variable",
    cargo: "Administrativos",
    estado_civil: "Sin Definir",
    num_hijos: 3,
    tipo_area: "Apoyo y Estructura",
    es_plantilla: true
  },
  {
    country: "3437799-0",
    nombre: "Laura",
    apellidos: "Ceballos",
    sexo: "Masculino",
    end_date: "2007-05-14",
    fecha_ingreso_grupo: "2017-12-09",
    fecha_nacimiento: "1974-01-15",
    fecha_renuncia: null,
    tipo_renuncia: null,
    division: "Tecnología y Operaciones",
    gerencia: "Activos Irreg y Recuperaciones",
    periodo: "11-2018",
    piramide: "Administrativos",
    tipo_contrato: "Indefinido",
    nombre_empresa: "Leniolabs",
    tipo_renta: "Renta Variable",
    cargo: "Administrativos",
    estado_civil: "Divorciado",
    num_hijos: 0,
    tipo_area: "Apoyo y Estructura",
    es_plantilla: true
  },
  {
    country: "7668100-0",
    nombre: "Jorge",
    apellidos: "Durán",
    sexo: "Femenino",
    end_date: "2007-05-14",
    fecha_ingreso_grupo: "2015-06-19",
    fecha_nacimiento: "1974-01-15",
    fecha_renuncia: null,
    tipo_renuncia: null,
    division: "Personas y Comunicación",
    gerencia: "Activos Irreg y Recuperaciones",
    periodo: "11-2018",
    piramide: "Administrativos",
    tipo_contrato: "Indefinido",
    nombre_empresa: "Santander",
    tipo_renta: "Renta Variable",
    cargo: "Profesionales y Tecnicos",
    estado_civil: "Conviviente Civil",
    num_hijos: 0,
    tipo_area: "Apoyo y Estructura",
    es_plantilla: true
  },
  {
    country: "1454823-0",
    nombre: "Carles",
    apellidos: "Olivo",
    sexo: "Femenino",
    end_date: "2007-05-14",
    fecha_ingreso_grupo: "2013-03-21",
    fecha_nacimiento: "1974-01-15",
    fecha_renuncia: null,
    tipo_renuncia: null,
    division: "Tecnología y Operaciones",
    gerencia: "Activos Irreg y Recuperaciones",
    periodo: "11-2018",
    piramide: "Administrativos",
    tipo_contrato: "Indefinido",
    nombre_empresa: "Leniolabs",
    tipo_renta: "Renta Variable",
    cargo: "Profesionales y Tecnicos",
    estado_civil: "Soltero(a)",
    num_hijos: 2,
    tipo_area: "Apoyo y Estructura",
    es_plantilla: true
  },
  {
    country: "241943-0",
    nombre: "Marta",
    apellidos: "Reyes",
    sexo: "Masculino",
    end_date: "2007-05-14",
    fecha_ingreso_grupo: "2016-10-09",
    fecha_nacimiento: "1974-01-15",
    fecha_renuncia: null,
    tipo_renuncia: null,
    division: "Financiera",
    gerencia: "Activos Irreg y Recuperaciones",
    periodo: "11-2018",
    piramide: "Administrativos",
    tipo_contrato: "Indefinido",
    nombre_empresa: "Santander",
    tipo_renta: "Renta Variable",
    cargo: "Jefaturas y Profesionales Sr",
    estado_civil: "Separado",
    num_hijos: 4,
    tipo_area: "Apoyo y Estructura",
    es_plantilla: true
  },
  {
    country: "8587747-0",
    nombre: "Iván",
    apellidos: "Aguilera",
    sexo: "Femenino",
    end_date: "2007-05-14",
    fecha_ingreso_grupo: "2015-02-24",
    fecha_nacimiento: "1974-01-15",
    fecha_renuncia: null,
    tipo_renuncia: null,
    division: "Clientes y Calidad",
    gerencia: "Activos Irreg y Recuperaciones",
    periodo: "11-2018",
    piramide: "Administrativos",
    tipo_contrato: "Indefinido",
    nombre_empresa: "Santander",
    tipo_renta: "Renta Variable",
    cargo: "Jefaturas y Profesionales Sr",
    estado_civil: "Casado(a)",
    num_hijos: 1,
    tipo_area: "Apoyo y Estructura",
    es_plantilla: true
  },
  {
    country: "4281387-0",
    nombre: "Marta",
    apellidos: "Berríos",
    sexo: "Masculino",
    end_date: "2007-05-14",
    fecha_ingreso_grupo: "2016-06-30",
    fecha_nacimiento: "1974-01-15",
    fecha_renuncia: null,
    tipo_renuncia: null,
    division: "Riesgos",
    gerencia: "Activos Irreg y Recuperaciones",
    periodo: "11-2018",
    piramide: "Administrativos",
    tipo_contrato: "Indefinido",
    nombre_empresa: "Santander",
    tipo_renta: "Renta Variable",
    cargo: "Profesionales y Tecnicos",
    estado_civil: "Sin Definir",
    num_hijos: 1,
    tipo_area: "Apoyo y Estructura",
    es_plantilla: true
  },
  {
    country: "8933124-0",
    nombre: "Manuel",
    apellidos: "Montes",
    sexo: "Femenino",
    end_date: "2007-05-14",
    fecha_ingreso_grupo: "2010-12-11",
    fecha_nacimiento: "1974-01-15",
    fecha_renuncia: null,
    tipo_renuncia: null,
    division: "Auditoria",
    gerencia: "Activos Irreg y Recuperaciones",
    periodo: "11-2018",
    piramide: "Administrativos",
    tipo_contrato: "Indefinido",
    nombre_empresa: "Santander",
    tipo_renta: "Renta Variable",
    cargo: "Administrativos",
    estado_civil: "Sin Definir",
    num_hijos: 3,
    tipo_area: "Apoyo y Estructura",
    es_plantilla: true
  },
  {
    country: "5782989-0",
    nombre: "Ana",
    apellidos: "Montalvo",
    sexo: "Masculino",
    end_date: "2007-05-14",
    fecha_ingreso_grupo: "2011-07-22",
    fecha_nacimiento: "1974-01-15",
    fecha_renuncia: null,
    tipo_renuncia: null,
    division: "Jurídica ",
    gerencia: "Activos Irreg y Recuperaciones",
    periodo: "11-2018",
    piramide: "Administrativos",
    tipo_contrato: "Indefinido",
    nombre_empresa: "Santander",
    tipo_renta: "Renta Variable",
    cargo: "Jefaturas y Profesionales Sr",
    estado_civil: "Soltero(a)",
    num_hijos: 4,
    tipo_area: "Apoyo y Estructura",
    es_plantilla: true
  },
  {
    country: "418763-0",
    nombre: "Marta",
    apellidos: "Leiva",
    sexo: "Masculino",
    end_date: "2007-05-14",
    fecha_ingreso_grupo: "2017-07-13",
    fecha_nacimiento: "1974-01-15",
    fecha_renuncia: null,
    tipo_renuncia: null,
    division: "Riesgos",
    gerencia: "Activos Irreg y Recuperaciones",
    periodo: "11-2018",
    piramide: "Administrativos",
    tipo_contrato: "Indefinido",
    nombre_empresa: "Santander",
    tipo_renta: "Renta Variable",
    cargo: "Profesionales y Tecnicos",
    estado_civil: "Divorciado",
    num_hijos: 4,
    tipo_area: "Apoyo y Estructura",
    es_plantilla: true
  },
  {
    country: "1517909-0",
    nombre: "Laura",
    apellidos: "Rocha",
    sexo: "Masculino",
    end_date: "2007-05-14",
    fecha_ingreso_grupo: "2018-05-21",
    fecha_nacimiento: "1974-01-15",
    fecha_renuncia: null,
    tipo_renuncia: null,
    division: "Banca Empresas e Intituciones",
    gerencia: "Activos Irreg y Recuperaciones",
    periodo: "11-2018",
    piramide: "Administrativos",
    tipo_contrato: "Indefinido",
    nombre_empresa: "Leniolabs",
    tipo_renta: "Renta Variable",
    cargo: "Gerentes",
    estado_civil: "Conviviente Civil",
    num_hijos: 1,
    tipo_area: "Apoyo y Estructura",
    es_plantilla: true
  },
  {
    country: "4008152-0",
    nombre: "Sergi",
    apellidos: "Meraz",
    sexo: "Femenino",
    end_date: "2007-05-14",
    fecha_ingreso_grupo: "2011-02-15",
    fecha_nacimiento: "1974-01-15",
    fecha_renuncia: null,
    tipo_renuncia: null,
    division: "Auditoria",
    gerencia: "Activos Irreg y Recuperaciones",
    periodo: "11-2018",
    piramide: "Administrativos",
    tipo_contrato: "Indefinido",
    nombre_empresa: "Santander",
    tipo_renta: "Renta Variable",
    cargo: "Administrativos",
    estado_civil: "Viudo(a)",
    num_hijos: 1,
    tipo_area: "Apoyo y Estructura",
    es_plantilla: true
  },
  {
    country: "747615-0",
    nombre: "Lorena",
    apellidos: "Treviño",
    sexo: "Masculino",
    end_date: "2007-05-14",
    fecha_ingreso_grupo: "2012-01-24",
    fecha_nacimiento: "1974-01-15",
    fecha_renuncia: null,
    tipo_renuncia: null,
    division: "Comercial",
    gerencia: "Activos Irreg y Recuperaciones",
    periodo: "11-2018",
    piramide: "Administrativos",
    tipo_contrato: "Indefinido",
    nombre_empresa: "Santander",
    tipo_renta: "Renta Variable",
    cargo: "Jefaturas y Profesionales Sr",
    estado_civil: "Conviviente Civil",
    num_hijos: 3,
    tipo_area: "Apoyo y Estructura",
    es_plantilla: true
  },
  {
    country: "5000362-0",
    nombre: "Salvador",
    apellidos: "Meléndez",
    sexo: "Femenino",
    end_date: "2007-05-14",
    fecha_ingreso_grupo: "2018-06-06",
    fecha_nacimiento: "1974-01-15",
    fecha_renuncia: null,
    tipo_renuncia: null,
    division: "Personas y Comunicación",
    gerencia: "Activos Irreg y Recuperaciones",
    periodo: "11-2018",
    piramide: "Administrativos",
    tipo_contrato: "Indefinido",
    nombre_empresa: "Santander",
    tipo_renta: "Renta Variable",
    cargo: "Profesionales y Tecnicos",
    estado_civil: "Separado",
    num_hijos: 3,
    tipo_area: "Apoyo y Estructura",
    es_plantilla: true
  },
  {
    country: "1828555-0",
    nombre: "Rubén",
    apellidos: "Dávila",
    sexo: "Femenino",
    end_date: "2007-05-14",
    fecha_ingreso_grupo: "2011-06-05",
    fecha_nacimiento: "1974-01-15",
    fecha_renuncia: null,
    tipo_renuncia: null,
    division: "Gerencia General",
    gerencia: "Activos Irreg y Recuperaciones",
    periodo: "11-2018",
    piramide: "Administrativos",
    tipo_contrato: "Indefinido",
    nombre_empresa: "Leniolabs",
    tipo_renta: "Renta Variable",
    cargo: "Profesionales y Tecnicos",
    estado_civil: "Sin Definir",
    num_hijos: 2,
    tipo_area: "Apoyo y Estructura",
    es_plantilla: true
  },
  {
    country: "1006743-0",
    nombre: "Josep",
    apellidos: "Farías",
    sexo: "Femenino",
    end_date: "2007-05-14",
    fecha_ingreso_grupo: "2017-11-13",
    fecha_nacimiento: "1974-01-15",
    fecha_renuncia: null,
    tipo_renuncia: null,
    division: "Clientes y Calidad",
    gerencia: "Activos Irreg y Recuperaciones",
    periodo: "11-2018",
    piramide: "Administrativos",
    tipo_contrato: "Indefinido",
    nombre_empresa: "Leniolabs",
    tipo_renta: "Renta Variable",
    cargo: "Administrativos",
    estado_civil: "Viudo(a)",
    num_hijos: 0,
    tipo_area: "Apoyo y Estructura",
    es_plantilla: true
  },
  {
    country: "866773-0",
    nombre: "Pedro",
    apellidos: "Córdova",
    sexo: "Femenino",
    end_date: "2007-05-14",
    fecha_ingreso_grupo: "2016-07-29",
    fecha_nacimiento: "1974-01-15",
    fecha_renuncia: null,
    tipo_renuncia: null,
    division: "Personas y Comunicación",
    gerencia: "Activos Irreg y Recuperaciones",
    periodo: "11-2018",
    piramide: "Administrativos",
    tipo_contrato: "Indefinido",
    nombre_empresa: "Leniolabs",
    tipo_renta: "Renta Variable",
    cargo: "Administrativos",
    estado_civil: "Divorciado",
    num_hijos: 0,
    tipo_area: "Apoyo y Estructura",
    es_plantilla: true
  },
  {
    country: "6758216-0",
    nombre: "Anni",
    apellidos: "Tamez",
    sexo: "Masculino",
    end_date: "2007-05-14",
    fecha_ingreso_grupo: "2012-04-29",
    fecha_nacimiento: "1974-01-15",
    fecha_renuncia: null,
    tipo_renuncia: null,
    division: "Personas y Comunicación",
    gerencia: "Activos Irreg y Recuperaciones",
    periodo: "11-2018",
    piramide: "Administrativos",
    tipo_contrato: "Indefinido",
    nombre_empresa: "Santander",
    tipo_renta: "Renta Variable",
    cargo: "Jefaturas y Profesionales Sr",
    estado_civil: "Conviviente Civil",
    num_hijos: 2,
    tipo_area: "Apoyo y Estructura",
    es_plantilla: true
  },
  {
    country: "6193543-0",
    nombre: "Josep",
    apellidos: "Montoya",
    sexo: "Femenino",
    end_date: "2007-05-14",
    fecha_ingreso_grupo: "2014-09-12",
    fecha_nacimiento: "1974-01-15",
    fecha_renuncia: null,
    tipo_renuncia: null,
    division: "Banca Empresas e Intituciones",
    gerencia: "Activos Irreg y Recuperaciones",
    periodo: "11-2018",
    piramide: "Administrativos",
    tipo_contrato: "Indefinido",
    nombre_empresa: "Santander",
    tipo_renta: "Renta Variable",
    cargo: "Administrativos",
    estado_civil: "Conviviente Civil",
    num_hijos: 3,
    tipo_area: "Apoyo y Estructura",
    es_plantilla: true
  },
  {
    country: "3732965-0",
    nombre: "Marta",
    apellidos: "Murillo",
    sexo: "Masculino",
    end_date: "2007-05-14",
    fecha_ingreso_grupo: "2019-04-24",
    fecha_nacimiento: "1974-01-15",
    fecha_renuncia: null,
    tipo_renuncia: null,
    division: "Financiera",
    gerencia: "Activos Irreg y Recuperaciones",
    periodo: "11-2018",
    piramide: "Administrativos",
    tipo_contrato: "Indefinido",
    nombre_empresa: "Santander",
    tipo_renta: "Renta Variable",
    cargo: "Jefaturas y Profesionales Sr",
    estado_civil: "Separado",
    num_hijos: 0,
    tipo_area: "Apoyo y Estructura",
    es_plantilla: true
  },
  {
    country: "5295624-0",
    nombre: "Jennifer",
    apellidos: "Armas",
    sexo: "Masculino",
    end_date: "2007-05-14",
    fecha_ingreso_grupo: "2018-08-02",
    fecha_nacimiento: "1974-01-15",
    fecha_renuncia: null,
    tipo_renuncia: null,
    division: "Auditoria",
    gerencia: "Activos Irreg y Recuperaciones",
    periodo: "11-2018",
    piramide: "Administrativos",
    tipo_contrato: "Indefinido",
    nombre_empresa: "Santander",
    tipo_renta: "Renta Variable",
    cargo: "Profesionales y Tecnicos",
    estado_civil: "Casado(a)",
    num_hijos: 3,
    tipo_area: "Apoyo y Estructura",
    es_plantilla: true
  },
  {
    country: "247924-0",
    nombre: "Rubén",
    apellidos: "Crespo",
    sexo: "Femenino",
    end_date: "2007-05-14",
    fecha_ingreso_grupo: "2015-12-16",
    fecha_nacimiento: "1974-01-15",
    fecha_renuncia: null,
    tipo_renuncia: null,
    division: "Jurídica ",
    gerencia: "Activos Irreg y Recuperaciones",
    periodo: "11-2018",
    piramide: "Administrativos",
    tipo_contrato: "Indefinido",
    nombre_empresa: "Leniolabs",
    tipo_renta: "Renta Variable",
    cargo: "Jefaturas y Profesionales Sr",
    estado_civil: "Soltero(a)",
    num_hijos: 1,
    tipo_area: "Apoyo y Estructura",
    es_plantilla: true
  },
  {
    country: "9386190-0",
    nombre: "Laura",
    apellidos: "Hernández",
    sexo: "Masculino",
    end_date: "2007-05-14",
    fecha_ingreso_grupo: "2018-01-10",
    fecha_nacimiento: "1974-01-15",
    fecha_renuncia: null,
    tipo_renuncia: null,
    division: "Financiera",
    gerencia: "Activos Irreg y Recuperaciones",
    periodo: "11-2018",
    piramide: "Administrativos",
    tipo_contrato: "Indefinido",
    nombre_empresa: "Santander",
    tipo_renta: "Renta Variable",
    cargo: "Jefaturas y Profesionales Sr",
    estado_civil: "Conviviente Civil",
    num_hijos: 2,
    tipo_area: "Apoyo y Estructura",
    es_plantilla: true
  },
  {
    country: "5724839-0",
    nombre: "Pedro",
    apellidos: "Montoya",
    sexo: "Femenino",
    end_date: "2007-05-14",
    fecha_ingreso_grupo: "2017-08-25",
    fecha_nacimiento: "1974-01-15",
    fecha_renuncia: null,
    tipo_renuncia: null,
    division: "Banca Empresas e Intituciones",
    gerencia: "Activos Irreg y Recuperaciones",
    periodo: "11-2018",
    piramide: "Administrativos",
    tipo_contrato: "Indefinido",
    nombre_empresa: "Leniolabs",
    tipo_renta: "Renta Variable",
    cargo: "Administrativos",
    estado_civil: "Conviviente Civil",
    num_hijos: 0,
    tipo_area: "Apoyo y Estructura",
    es_plantilla: true
  },
  {
    country: "2792986-0",
    nombre: "Pedro",
    apellidos: "Delapaz",
    sexo: "Femenino",
    end_date: "2007-05-14",
    fecha_ingreso_grupo: "2018-01-04",
    fecha_nacimiento: "1974-01-15",
    fecha_renuncia: null,
    tipo_renuncia: null,
    division: "Auditoria",
    gerencia: "Activos Irreg y Recuperaciones",
    periodo: "11-2018",
    piramide: "Administrativos",
    tipo_contrato: "Indefinido",
    nombre_empresa: "Leniolabs",
    tipo_renta: "Renta Variable",
    cargo: "Gerentes",
    estado_civil: "Conviviente Civil",
    num_hijos: 4,
    tipo_area: "Apoyo y Estructura",
    es_plantilla: true
  },
  {
    country: "6831067-0",
    nombre: "Miguel",
    apellidos: "Paredes",
    sexo: "Femenino",
    end_date: "2007-05-14",
    fecha_ingreso_grupo: "2010-02-03",
    fecha_nacimiento: "1974-01-15",
    fecha_renuncia: null,
    tipo_renuncia: null,
    division: "Tecnología y Operaciones",
    gerencia: "Activos Irreg y Recuperaciones",
    periodo: "11-2018",
    piramide: "Administrativos",
    tipo_contrato: "Indefinido",
    nombre_empresa: "Santander",
    tipo_renta: "Renta Variable",
    cargo: "Gerentes",
    estado_civil: "Conviviente Civil",
    num_hijos: 3,
    tipo_area: "Apoyo y Estructura",
    es_plantilla: true
  },
  {
    country: "1334091-0",
    nombre: "Andrea",
    apellidos: "Caraballo",
    sexo: "Masculino",
    end_date: "2007-05-14",
    fecha_ingreso_grupo: "2011-05-24",
    fecha_nacimiento: "1974-01-15",
    fecha_renuncia: null,
    tipo_renuncia: null,
    division: "Financiera",
    gerencia: "Activos Irreg y Recuperaciones",
    periodo: "11-2018",
    piramide: "Administrativos",
    tipo_contrato: "Indefinido",
    nombre_empresa: "Santander",
    tipo_renta: "Renta Variable",
    cargo: "Profesionales y Tecnicos",
    estado_civil: "Casado(a)",
    num_hijos: 1,
    tipo_area: "Apoyo y Estructura",
    es_plantilla: true
  },
  {
    country: "989394-0",
    nombre: "Marta",
    apellidos: "Solano",
    sexo: "Masculino",
    end_date: "2007-05-14",
    fecha_ingreso_grupo: "2020-01-19",
    fecha_nacimiento: "1974-01-15",
    fecha_renuncia: null,
    tipo_renuncia: null,
    division: "Riesgos",
    gerencia: "Activos Irreg y Recuperaciones",
    periodo: "11-2018",
    piramide: "Administrativos",
    tipo_contrato: "Indefinido",
    nombre_empresa: "Santander",
    tipo_renta: "Renta Variable",
    cargo: "Administrativos",
    estado_civil: "Conviviente Civil",
    num_hijos: 2,
    tipo_area: "Apoyo y Estructura",
    es_plantilla: true
  },
  {
    country: "5031022-0",
    nombre: "Sergi",
    apellidos: "Muñoz",
    sexo: "Femenino",
    end_date: "2007-05-14",
    fecha_ingreso_grupo: "2019-09-16",
    fecha_nacimiento: "1974-01-15",
    fecha_renuncia: null,
    tipo_renuncia: null,
    division: "Riesgos",
    gerencia: "Activos Irreg y Recuperaciones",
    periodo: "11-2018",
    piramide: "Administrativos",
    tipo_contrato: "Indefinido",
    nombre_empresa: "Leniolabs",
    tipo_renta: "Renta Variable",
    cargo: "Administrativos",
    estado_civil: "Separado",
    num_hijos: 0,
    tipo_area: "Apoyo y Estructura",
    es_plantilla: true
  },
  {
    country: "2631462-0",
    nombre: "Manuel",
    apellidos: "Sepúlveda",
    sexo: "Femenino",
    end_date: "2007-05-14",
    fecha_ingreso_grupo: "2018-05-23",
    fecha_nacimiento: "1974-01-15",
    fecha_renuncia: null,
    tipo_renuncia: null,
    division: "Riesgos",
    gerencia: "Activos Irreg y Recuperaciones",
    periodo: "11-2018",
    piramide: "Administrativos",
    tipo_contrato: "Indefinido",
    nombre_empresa: "Leniolabs",
    tipo_renta: "Renta Variable",
    cargo: "Profesionales y Tecnicos",
    estado_civil: "Conviviente Civil",
    num_hijos: 2,
    tipo_area: "Apoyo y Estructura",
    es_plantilla: true
  },
  {
    country: "5711497-0",
    nombre: "Manuel",
    apellidos: "Agosto",
    sexo: "Femenino",
    end_date: "2007-05-14",
    fecha_ingreso_grupo: "2011-11-06",
    fecha_nacimiento: "1974-01-15",
    fecha_renuncia: null,
    tipo_renuncia: null,
    division: "Clientes y Calidad",
    gerencia: "Activos Irreg y Recuperaciones",
    periodo: "11-2018",
    piramide: "Administrativos",
    tipo_contrato: "Indefinido",
    nombre_empresa: "Santander",
    tipo_renta: "Renta Variable",
    cargo: "Profesionales y Tecnicos",
    estado_civil: "Casado(a)",
    num_hijos: 3,
    tipo_area: "Apoyo y Estructura",
    es_plantilla: true
  },
  {
    country: "7976343-0",
    nombre: "Jordi",
    apellidos: "Alvarado",
    sexo: "Femenino",
    end_date: "2007-05-14",
    fecha_ingreso_grupo: "2014-03-20",
    fecha_nacimiento: "1974-01-15",
    fecha_renuncia: null,
    tipo_renuncia: null,
    division: "Auditoria",
    gerencia: "Activos Irreg y Recuperaciones",
    periodo: "11-2018",
    piramide: "Administrativos",
    tipo_contrato: "Indefinido",
    nombre_empresa: "Leniolabs",
    tipo_renta: "Renta Variable",
    cargo: "Profesionales y Tecnicos",
    estado_civil: "Soltero(a)",
    num_hijos: 0,
    tipo_area: "Apoyo y Estructura",
    es_plantilla: true
  },
  {
    country: "9676910-0",
    nombre: "Manuel",
    apellidos: "Alarcón",
    sexo: "Femenino",
    end_date: "2007-05-14",
    fecha_ingreso_grupo: "2017-01-02",
    fecha_nacimiento: "1974-01-15",
    fecha_renuncia: null,
    tipo_renuncia: null,
    division: "Tecnología y Operaciones",
    gerencia: "Activos Irreg y Recuperaciones",
    periodo: "11-2018",
    piramide: "Administrativos",
    tipo_contrato: "Indefinido",
    nombre_empresa: "Santander",
    tipo_renta: "Renta Variable",
    cargo: "Gerentes",
    estado_civil: "Soltero(a)",
    num_hijos: 0,
    tipo_area: "Apoyo y Estructura",
    es_plantilla: true
  },
  {
    country: "5392180-0",
    nombre: "Miguel",
    apellidos: "Gamboa",
    sexo: "Femenino",
    end_date: "2007-05-14",
    fecha_ingreso_grupo: "2016-08-11",
    fecha_nacimiento: "1974-01-15",
    fecha_renuncia: null,
    tipo_renuncia: null,
    division: "Tecnología y Operaciones",
    gerencia: "Activos Irreg y Recuperaciones",
    periodo: "11-2018",
    piramide: "Administrativos",
    tipo_contrato: "Indefinido",
    nombre_empresa: "Leniolabs",
    tipo_renta: "Renta Variable",
    cargo: "Profesionales y Tecnicos",
    estado_civil: "Divorciado",
    num_hijos: 0,
    tipo_area: "Apoyo y Estructura",
    es_plantilla: true
  },
  {
    country: "7918001-0",
    nombre: "Ana",
    apellidos: "Miramontes",
    sexo: "Masculino",
    end_date: "2007-05-14",
    fecha_ingreso_grupo: "2017-11-02",
    fecha_nacimiento: "1974-01-15",
    fecha_renuncia: null,
    tipo_renuncia: null,
    division: "Riesgos",
    gerencia: "Activos Irreg y Recuperaciones",
    periodo: "11-2018",
    piramide: "Administrativos",
    tipo_contrato: "Indefinido",
    nombre_empresa: "Santander",
    tipo_renta: "Renta Variable",
    cargo: "Jefaturas y Profesionales Sr",
    estado_civil: "Sin Definir",
    num_hijos: 3,
    tipo_area: "Apoyo y Estructura",
    es_plantilla: true
  },
  {
    country: "5120682-0",
    nombre: "Josep",
    apellidos: "Valentín",
    sexo: "Femenino",
    end_date: "2007-05-14",
    fecha_ingreso_grupo: "2018-03-05",
    fecha_nacimiento: "1974-01-15",
    fecha_renuncia: null,
    tipo_renuncia: null,
    division: "Banca Empresas e Intituciones",
    gerencia: "Activos Irreg y Recuperaciones",
    periodo: "11-2018",
    piramide: "Administrativos",
    tipo_contrato: "Indefinido",
    nombre_empresa: "Santander",
    tipo_renta: "Renta Variable",
    cargo: "Profesionales y Tecnicos",
    estado_civil: "Conviviente Civil",
    num_hijos: 0,
    tipo_area: "Apoyo y Estructura",
    es_plantilla: true
  },
  {
    country: "7314072-0",
    nombre: "Pedro",
    apellidos: "Sauceda",
    sexo: "Femenino",
    end_date: "2007-05-14",
    fecha_ingreso_grupo: "2015-02-22",
    fecha_nacimiento: "1974-01-15",
    fecha_renuncia: null,
    tipo_renuncia: null,
    division: "Jurídica ",
    gerencia: "Activos Irreg y Recuperaciones",
    periodo: "11-2018",
    piramide: "Administrativos",
    tipo_contrato: "Indefinido",
    nombre_empresa: "Santander",
    tipo_renta: "Renta Variable",
    cargo: "Gerentes",
    estado_civil: "Divorciado",
    num_hijos: 1,
    tipo_area: "Apoyo y Estructura",
    es_plantilla: true
  },
  {
    country: "3649541-0",
    nombre: "Roser",
    apellidos: "Alicea",
    sexo: "Masculino",
    end_date: "2007-05-14",
    fecha_ingreso_grupo: "2018-05-25",
    fecha_nacimiento: "1974-01-15",
    fecha_renuncia: null,
    tipo_renuncia: null,
    division: "Banca Empresas e Intituciones",
    gerencia: "Activos Irreg y Recuperaciones",
    periodo: "11-2018",
    piramide: "Administrativos",
    tipo_contrato: "Indefinido",
    nombre_empresa: "Leniolabs",
    tipo_renta: "Renta Variable",
    cargo: "Administrativos",
    estado_civil: "Separado",
    num_hijos: 0,
    tipo_area: "Apoyo y Estructura",
    es_plantilla: true
  },
  {
    country: "9979222-0",
    nombre: "Laura",
    apellidos: "Malave",
    sexo: "Masculino",
    end_date: "2007-05-14",
    fecha_ingreso_grupo: "2011-03-19",
    fecha_nacimiento: "1974-01-15",
    fecha_renuncia: null,
    tipo_renuncia: null,
    division: "Financiera",
    gerencia: "Activos Irreg y Recuperaciones",
    periodo: "11-2018",
    piramide: "Administrativos",
    tipo_contrato: "Indefinido",
    nombre_empresa: "Santander",
    tipo_renta: "Renta Variable",
    cargo: "Administrativos",
    estado_civil: "Casado(a)",
    num_hijos: 0,
    tipo_area: "Apoyo y Estructura",
    es_plantilla: true
  },
  {
    country: "9724533-0",
    nombre: "Andrea",
    apellidos: "Alanis",
    sexo: "Masculino",
    end_date: "2007-05-14",
    fecha_ingreso_grupo: "2016-04-22",
    fecha_nacimiento: "1974-01-15",
    fecha_renuncia: null,
    tipo_renuncia: null,
    division: "Tecnología y Operaciones",
    gerencia: "Activos Irreg y Recuperaciones",
    periodo: "11-2018",
    piramide: "Administrativos",
    tipo_contrato: "Indefinido",
    nombre_empresa: "Santander",
    tipo_renta: "Renta Variable",
    cargo: "Profesionales y Tecnicos",
    estado_civil: "Sin Definir",
    num_hijos: 4,
    tipo_area: "Apoyo y Estructura",
    es_plantilla: true
  },
  {
    country: "2911393-0",
    nombre: "Miguel",
    apellidos: "Solano",
    sexo: "Femenino",
    end_date: "2007-05-14",
    fecha_ingreso_grupo: "2018-11-20",
    fecha_nacimiento: "1974-01-15",
    fecha_renuncia: null,
    tipo_renuncia: null,
    division: "Banca Empresas e Intituciones",
    gerencia: "Activos Irreg y Recuperaciones",
    periodo: "11-2018",
    piramide: "Administrativos",
    tipo_contrato: "Indefinido",
    nombre_empresa: "Santander",
    tipo_renta: "Renta Variable",
    cargo: "Jefaturas y Profesionales Sr",
    estado_civil: "Casado(a)",
    num_hijos: 1,
    tipo_area: "Apoyo y Estructura",
    es_plantilla: true
  },
  {
    country: "8894028-0",
    nombre: "Marta",
    apellidos: "Laureano",
    sexo: "Masculino",
    end_date: "2007-05-14",
    fecha_ingreso_grupo: "2018-06-15",
    fecha_nacimiento: "1974-01-15",
    fecha_renuncia: null,
    tipo_renuncia: null,
    division: "Banca Empresas e Intituciones",
    gerencia: "Activos Irreg y Recuperaciones",
    periodo: "11-2018",
    piramide: "Administrativos",
    tipo_contrato: "Indefinido",
    nombre_empresa: "Leniolabs",
    tipo_renta: "Renta Variable",
    cargo: "Administrativos",
    estado_civil: "Sin Definir",
    num_hijos: 1,
    tipo_area: "Apoyo y Estructura",
    es_plantilla: true
  },
  {
    country: "3940305-0",
    nombre: "Marta",
    apellidos: "Arce",
    sexo: "Masculino",
    end_date: "2007-05-14",
    fecha_ingreso_grupo: "2016-12-28",
    fecha_nacimiento: "1974-01-15",
    fecha_renuncia: null,
    tipo_renuncia: null,
    division: "Banca Empresas e Intituciones",
    gerencia: "Activos Irreg y Recuperaciones",
    periodo: "11-2018",
    piramide: "Administrativos",
    tipo_contrato: "Indefinido",
    nombre_empresa: "Leniolabs",
    tipo_renta: "Renta Variable",
    cargo: "Administrativos",
    estado_civil: "Conviviente Civil",
    num_hijos: 0,
    tipo_area: "Apoyo y Estructura",
    es_plantilla: true
  },
  {
    country: "6417481-0",
    nombre: "Laura",
    apellidos: "Arroyo",
    sexo: "Masculino",
    end_date: "2007-05-14",
    fecha_ingreso_grupo: "2016-04-29",
    fecha_nacimiento: "1974-01-15",
    fecha_renuncia: null,
    tipo_renuncia: null,
    division: "Gerencia General",
    gerencia: "Activos Irreg y Recuperaciones",
    periodo: "11-2018",
    piramide: "Administrativos",
    tipo_contrato: "Indefinido",
    nombre_empresa: "Leniolabs",
    tipo_renta: "Renta Variable",
    cargo: "Profesionales y Tecnicos",
    estado_civil: "Separado",
    num_hijos: 0,
    tipo_area: "Apoyo y Estructura",
    es_plantilla: true
  },
  {
    country: "6522313-0",
    nombre: "Daniel",
    apellidos: "Valdivia",
    sexo: "Femenino",
    end_date: "2007-05-14",
    fecha_ingreso_grupo: "2011-10-31",
    fecha_nacimiento: "1974-01-15",
    fecha_renuncia: null,
    tipo_renuncia: null,
    division: "Clientes y Calidad",
    gerencia: "Activos Irreg y Recuperaciones",
    periodo: "11-2018",
    piramide: "Administrativos",
    tipo_contrato: "Indefinido",
    nombre_empresa: "Leniolabs",
    tipo_renta: "Renta Variable",
    cargo: "Gerentes",
    estado_civil: "Separado",
    num_hijos: 1,
    tipo_area: "Apoyo y Estructura",
    es_plantilla: true
  },
  {
    country: "5351906-0",
    nombre: "Laura",
    apellidos: "Gaytán",
    sexo: "Masculino",
    end_date: "2007-05-14",
    fecha_ingreso_grupo: "2011-04-19",
    fecha_nacimiento: "1974-01-15",
    fecha_renuncia: null,
    tipo_renuncia: null,
    division: "Financiera",
    gerencia: "Activos Irreg y Recuperaciones",
    periodo: "11-2018",
    piramide: "Administrativos",
    tipo_contrato: "Indefinido",
    nombre_empresa: "Santander",
    tipo_renta: "Renta Variable",
    cargo: "Jefaturas y Profesionales Sr",
    estado_civil: "Soltero(a)",
    num_hijos: 3,
    tipo_area: "Apoyo y Estructura",
    es_plantilla: true
  },
  {
    country: "3708619-0",
    nombre: "Pedro",
    apellidos: "Montaño",
    sexo: "Femenino",
    end_date: "2007-05-14",
    fecha_ingreso_grupo: "2010-04-06",
    fecha_nacimiento: "1974-01-15",
    fecha_renuncia: null,
    tipo_renuncia: null,
    division: "Tecnología y Operaciones",
    gerencia: "Activos Irreg y Recuperaciones",
    periodo: "11-2018",
    piramide: "Administrativos",
    tipo_contrato: "Indefinido",
    nombre_empresa: "Santander",
    tipo_renta: "Renta Variable",
    cargo: "Administrativos",
    estado_civil: "Separado",
    num_hijos: 2,
    tipo_area: "Apoyo y Estructura",
    es_plantilla: true
  },
  {
    country: "5668685-0",
    nombre: "Sergi",
    apellidos: "Cotto",
    sexo: "Femenino",
    end_date: "2007-05-14",
    fecha_ingreso_grupo: "2017-04-09",
    fecha_nacimiento: "1974-01-15",
    fecha_renuncia: null,
    tipo_renuncia: null,
    division: "Riesgos",
    gerencia: "Activos Irreg y Recuperaciones",
    periodo: "11-2018",
    piramide: "Administrativos",
    tipo_contrato: "Indefinido",
    nombre_empresa: "Leniolabs",
    tipo_renta: "Renta Variable",
    cargo: "Profesionales y Tecnicos",
    estado_civil: "Soltero(a)",
    num_hijos: 0,
    tipo_area: "Apoyo y Estructura",
    es_plantilla: true
  },
  {
    country: "4657138-0",
    nombre: "Laura",
    apellidos: "Báez",
    sexo: "Masculino",
    end_date: "2007-05-14",
    fecha_ingreso_grupo: "2020-04-28",
    fecha_nacimiento: "1974-01-15",
    fecha_renuncia: null,
    tipo_renuncia: null,
    division: "Clientes y Calidad",
    gerencia: "Activos Irreg y Recuperaciones",
    periodo: "11-2018",
    piramide: "Administrativos",
    tipo_contrato: "Indefinido",
    nombre_empresa: "Santander",
    tipo_renta: "Renta Variable",
    cargo: "Jefaturas y Profesionales Sr",
    estado_civil: "Viudo(a)",
    num_hijos: 3,
    tipo_area: "Apoyo y Estructura",
    es_plantilla: true
  },
  {
    country: "4795696-0",
    nombre: "Josep",
    apellidos: "Sánchez",
    sexo: "Femenino",
    end_date: "2007-05-14",
    fecha_ingreso_grupo: "2016-06-24",
    fecha_nacimiento: "1974-01-15",
    fecha_renuncia: null,
    tipo_renuncia: null,
    division: "Gerencia General",
    gerencia: "Activos Irreg y Recuperaciones",
    periodo: "11-2018",
    piramide: "Administrativos",
    tipo_contrato: "Indefinido",
    nombre_empresa: "Leniolabs",
    tipo_renta: "Renta Variable",
    cargo: "Profesionales y Tecnicos",
    estado_civil: "Sin Definir",
    num_hijos: 0,
    tipo_area: "Apoyo y Estructura",
    es_plantilla: true
  },
  {
    country: "1409417-0",
    nombre: "Jordi",
    apellidos: "Ochoa",
    sexo: "Femenino",
    end_date: "2007-05-14",
    fecha_ingreso_grupo: "2014-05-23",
    fecha_nacimiento: "1974-01-15",
    fecha_renuncia: null,
    tipo_renuncia: null,
    division: "Jurídica ",
    gerencia: "Activos Irreg y Recuperaciones",
    periodo: "11-2018",
    piramide: "Administrativos",
    tipo_contrato: "Indefinido",
    nombre_empresa: "Santander",
    tipo_renta: "Renta Variable",
    cargo: "Profesionales y Tecnicos",
    estado_civil: "Viudo(a)",
    num_hijos: 0,
    tipo_area: "Apoyo y Estructura",
    es_plantilla: true
  },
  {
    country: "6418129-0",
    nombre: "Roser",
    apellidos: "Garrido",
    sexo: "Masculino",
    end_date: "2007-05-14",
    fecha_ingreso_grupo: "2020-03-03",
    fecha_nacimiento: "1974-01-15",
    fecha_renuncia: null,
    tipo_renuncia: null,
    division: "Financiera",
    gerencia: "Activos Irreg y Recuperaciones",
    periodo: "11-2018",
    piramide: "Administrativos",
    tipo_contrato: "Indefinido",
    nombre_empresa: "Leniolabs",
    tipo_renta: "Renta Variable",
    cargo: "Administrativos",
    estado_civil: "Casado(a)",
    num_hijos: 3,
    tipo_area: "Apoyo y Estructura",
    es_plantilla: true
  },
  {
    country: "4994833-0",
    nombre: "Roser",
    apellidos: "Toro",
    sexo: "Masculino",
    end_date: "2007-05-14",
    fecha_ingreso_grupo: "2013-03-28",
    fecha_nacimiento: "1974-01-15",
    fecha_renuncia: null,
    tipo_renuncia: null,
    division: "Jurídica ",
    gerencia: "Activos Irreg y Recuperaciones",
    periodo: "11-2018",
    piramide: "Administrativos",
    tipo_contrato: "Indefinido",
    nombre_empresa: "Leniolabs",
    tipo_renta: "Renta Variable",
    cargo: "Profesionales y Tecnicos",
    estado_civil: "Divorciado",
    num_hijos: 0,
    tipo_area: "Apoyo y Estructura",
    es_plantilla: true
  },
  {
    country: "798621-0",
    nombre: "Jennifer",
    apellidos: "Valdés",
    sexo: "Masculino",
    end_date: "2007-05-14",
    fecha_ingreso_grupo: "2011-04-18",
    fecha_nacimiento: "1974-01-15",
    fecha_renuncia: null,
    tipo_renuncia: null,
    division: "Clientes y Calidad",
    gerencia: "Activos Irreg y Recuperaciones",
    periodo: "11-2018",
    piramide: "Administrativos",
    tipo_contrato: "Indefinido",
    nombre_empresa: "Santander",
    tipo_renta: "Renta Variable",
    cargo: "Gerentes",
    estado_civil: "Viudo(a)",
    num_hijos: 0,
    tipo_area: "Apoyo y Estructura",
    es_plantilla: true
  },
  {
    country: "9082774-0",
    nombre: "Ricardo",
    apellidos: "Ordóñez",
    sexo: "Femenino",
    end_date: "2007-05-14",
    fecha_ingreso_grupo: "2011-07-23",
    fecha_nacimiento: "1974-01-15",
    fecha_renuncia: null,
    tipo_renuncia: null,
    division: "Tecnología y Operaciones",
    gerencia: "Activos Irreg y Recuperaciones",
    periodo: "11-2018",
    piramide: "Administrativos",
    tipo_contrato: "Indefinido",
    nombre_empresa: "Santander",
    tipo_renta: "Renta Variable",
    cargo: "Jefaturas y Profesionales Sr",
    estado_civil: "Viudo(a)",
    num_hijos: 0,
    tipo_area: "Apoyo y Estructura",
    es_plantilla: true
  },
  {
    country: "7007242-0",
    nombre: "Matilde",
    apellidos: "Ornelas",
    sexo: "Masculino",
    end_date: "2007-05-14",
    fecha_ingreso_grupo: "2018-07-10",
    fecha_nacimiento: "1974-01-15",
    fecha_renuncia: null,
    tipo_renuncia: null,
    division: "Tecnología y Operaciones",
    gerencia: "Activos Irreg y Recuperaciones",
    periodo: "11-2018",
    piramide: "Administrativos",
    tipo_contrato: "Indefinido",
    nombre_empresa: "Leniolabs",
    tipo_renta: "Renta Variable",
    cargo: "Jefaturas y Profesionales Sr",
    estado_civil: "Soltero(a)",
    num_hijos: 2,
    tipo_area: "Apoyo y Estructura",
    es_plantilla: true
  },
  {
    country: "4023038-0",
    nombre: "Ricardo",
    apellidos: "Olivárez",
    sexo: "Femenino",
    end_date: "2007-05-14",
    fecha_ingreso_grupo: "2018-05-30",
    fecha_nacimiento: "1974-01-15",
    fecha_renuncia: null,
    tipo_renuncia: null,
    division: "Gerencia General",
    gerencia: "Activos Irreg y Recuperaciones",
    periodo: "11-2018",
    piramide: "Administrativos",
    tipo_contrato: "Indefinido",
    nombre_empresa: "Santander",
    tipo_renta: "Renta Variable",
    cargo: "Profesionales y Tecnicos",
    estado_civil: "Sin Definir",
    num_hijos: 4,
    tipo_area: "Apoyo y Estructura",
    es_plantilla: true
  },
  {
    country: "9987637-0",
    nombre: "Laura",
    apellidos: "Espinosa",
    sexo: "Masculino",
    end_date: "2007-05-14",
    fecha_ingreso_grupo: "2013-02-28",
    fecha_nacimiento: "1974-01-15",
    fecha_renuncia: null,
    tipo_renuncia: null,
    division: "Comercial",
    gerencia: "Activos Irreg y Recuperaciones",
    periodo: "11-2018",
    piramide: "Administrativos",
    tipo_contrato: "Indefinido",
    nombre_empresa: "Santander",
    tipo_renta: "Renta Variable",
    cargo: "Profesionales y Tecnicos",
    estado_civil: "Sin Definir",
    num_hijos: 4,
    tipo_area: "Apoyo y Estructura",
    es_plantilla: true
  },
  {
    country: "6531796-0",
    nombre: "Anni",
    apellidos: "Quiróz",
    sexo: "Masculino",
    end_date: "2007-05-14",
    fecha_ingreso_grupo: "2017-08-05",
    fecha_nacimiento: "1974-01-15",
    fecha_renuncia: null,
    tipo_renuncia: null,
    division: "Gerencia General",
    gerencia: "Activos Irreg y Recuperaciones",
    periodo: "11-2018",
    piramide: "Administrativos",
    tipo_contrato: "Indefinido",
    nombre_empresa: "Santander",
    tipo_renta: "Renta Variable",
    cargo: "Jefaturas y Profesionales Sr",
    estado_civil: "Viudo(a)",
    num_hijos: 1,
    tipo_area: "Apoyo y Estructura",
    es_plantilla: true
  },
  {
    country: "2944395-0",
    nombre: "Lorena",
    apellidos: "Aponte",
    sexo: "Masculino",
    end_date: "2007-05-14",
    fecha_ingreso_grupo: "2016-10-30",
    fecha_nacimiento: "1974-01-15",
    fecha_renuncia: null,
    tipo_renuncia: null,
    division: "Comercial",
    gerencia: "Activos Irreg y Recuperaciones",
    periodo: "11-2018",
    piramide: "Administrativos",
    tipo_contrato: "Indefinido",
    nombre_empresa: "Santander",
    tipo_renta: "Renta Variable",
    cargo: "Profesionales y Tecnicos",
    estado_civil: "Divorciado",
    num_hijos: 0,
    tipo_area: "Apoyo y Estructura",
    es_plantilla: true
  }
];
